interface SiteItem {
  name: string;
  url: string;
  displayUrl: string;
  desc: string;
  favicon: string;
  faviconBg: string;
  tag: string;
  tagBg: string;
  tagColor: string;
  accent: string;
}

interface Category {
  id: string;
  icon: string;
  name: string;
  desc: string;
  iconBg: string;
  sites: SiteItem[];
}

export const categories: Category[] = [
  {
    id: "source",
    icon: "🛜",
    name: "资源网站",
    desc: "全网资源网站，涵盖影视、音乐、软件等",
    iconBg: "rgba(241, 132, 99, 0.15)",
    sites: [
      {
        name: "橘子的分享",
        url: "https://orangecj.cn",
        displayUrl: "orangecj.cn",
        desc: "自己看的资源",
        favicon: "橘",
        faviconBg: "#e99527",
        tag: "百度、夸克资源",
        tagBg: "rgba(223, 143, 23, 0.12)",
        tagColor: "#e99527",
        accent: "#e99527",
      },
      {
        name: "3y论坛",
        url: "https://www.3ylt.xyz",
        displayUrl: "www.3ylt.xyz",
        desc: "纯净的网盘资源分享社区",
        favicon: "3y",
        faviconBg: "#c2c2c2",
        tag: "百度、夸克资源",
        tagBg: "rgba(240, 240, 240, 0.12)",
        tagColor: "#c2c2c2",
        accent: "#c2c2c2",
      },
      {
        name: "光鸭资源社",
        url: "https://www.guangya.cc/",
        displayUrl: "www.guangya.cc",
        desc: "专注免费分享光鸭云盘资源",
        favicon: "光",
        faviconBg: "#d46b07",
        tag: "光鸭资源",
        tagBg: "rgba(212, 107, 7,.12)",
        tagColor: "#d46b07",
        accent: "#d46b07",
      },
      {
        name: "海盗湾",
        url: "https://thepiratebay.org/",
        displayUrl: "thepiratebay.org/",
        desc: "海盗湾磁力网站，需要科学上网",
        favicon: "海",
        faviconBg: "#a3734d",
        tag: "磁力网站",
        tagBg: "rgba(163, 115, 77,.12)",
        tagColor: "#a3734d",
        accent: "#a3734d",
      },
      {
        name: "uindex",
        url: "https://uindex.org/",
        displayUrl: "uindex.org/",
        desc: "uindex磁力网站，需要科学上网",
        favicon: "U",
        faviconBg: "#5ebb1e",
        tag: "磁力网站",
        tagBg: "rgba(94, 187, 30,.12)",
        tagColor: "#5ebb1e",
        accent: "#5ebb1e",
      },
      {
        name: "纸鸳磁力",
        url: "https://magnet.kiteyuan.info/",
        displayUrl: "magnet.kiteyuan.info/",
        desc: "纸鸳磁力聚合网站",
        favicon: "鸳",
        faviconBg: "#005bc0",
        tag: "磁力网站",
        tagBg: "rgb(0, 91, 192,.12)",
        tagColor: "#005bc0",
        accent: "#005bc0",
      },
      {
        name: "BT磁力",
        url: "https://www.btbtla.com/",
        displayUrl: "www.btbtla.com/",
        desc: "BT磁力网站，我用的比较多的磁力网站",
        favicon: "BT",
        faviconBg: "rgb(220, 93, 31)",
        tag: "磁力网站",
        tagBg: "rgb(220, 93, 31,.12)",
        tagColor: "rgb(220, 93, 31)",
        accent: "rgb(220, 93, 31)",
      },
      {
        name: "电影天堂",
        url: "https://www.xl720.com/",
        displayUrl: "www.xl720.com/",
        desc: "用过的都懂，这个网站版本很多",
        favicon: "影",
        faviconBg: "rgb(31, 138, 204)",
        tag: "磁力网站",
        tagBg: "rgb(31, 138, 204,.12)",
        tagColor: "rgb(31, 138, 204)",
        accent: "rgb(31, 138, 204)",
      },
    ],
  },
  {
    id: "video",
    icon: "🎬",
    name: "影视娱乐",
    desc: "追剧观影、视频创作一站式直达",
    iconBg: "rgba(239,68,68,0.15)",
    sites: [
      {
        name: "爱壹帆",
        url: "https://www.yifan.tv/",
        displayUrl: "www.yifan.tv",
        desc: "海量高清视频免费在线观看",
        favicon: "爱",
        faviconBg: "#6addff",
        tag: "影视网站",
        tagBg: "rgba(106, 221, 255,.12)",
        tagColor: "#6addff",
        accent: "#6addff",
      },
      {
        name: "泥巴影院",
        url: "https://nbyy.tv/",
        displayUrl: "nbyy.tv/",
        desc: "海外华人在线影院",
        favicon: "泥",
        faviconBg: "#f3c232",
        tag: "影视网站",
        tagBg: "rgba(243, 194, 50,.12)",
        tagColor: "#f3c232",
        accent: "#f3c232",
      },
      {
        name: "奈飞工厂",
        url: "https://yanetflix.com/",
        displayUrl: "yanetflix.com/",
        desc: "一个致力于免费提供Netflix影剧动漫的流媒体播放平台",
        favicon: "奈",
        faviconBg: "#e10916",
        tag: "影视网站",
        tagBg: "rgba(225, 9, 22,.12)",
        tagColor: "#e10916",
        accent: "#e10916",
      },
      {
        name: "爱迪影视",
        url: "https://aidi.tv/",
        displayUrl: "aidi.tv/",
        desc: "爱迪影视分享4K资源,1080P高清,Netflix奈菲最新电影,韩剧,日剧,电视剧,欧美剧,动漫等在线观看。",
        favicon: "爱",
        faviconBg: "#3fcf92",
        tag: "影视网站",
        tagBg: "rgba(63, 207, 146,.12)",
        tagColor: "#3fcf92",
        accent: "#3fcf92",
      },
      {
        name: "哔哩哔哩",
        url: "https://www.bilibili.com",
        displayUrl: "bilibili.com",
        desc: "年轻人喜爱的弹幕视频网站，涵盖动画、游戏、知识等丰富内容",
        favicon: "B",
        faviconBg: "#fb7299",
        tag: "视频平台",
        tagBg: "rgba(251,114,153,0.12)",
        tagColor: "#fb7299",
        accent: "#fb7299",
      },
      {
        name: "YouTube",
        url: "https://www.youtube.com",
        displayUrl: "youtube.com",
        desc: "全球最大的视频分享平台，海量创作者内容和多元频道",
        favicon: "Y",
        faviconBg: "#ff0000",
        tag: "视频平台",
        tagBg: "rgba(255,0,0,0.12)",
        tagColor: "#ff5252",
        accent: "#ff0000",
      },
      {
        name: "Netflix",
        url: "https://www.netflix.com",
        displayUrl: "netflix.com",
        desc: "全球领先的流媒体平台，原创剧集、电影和纪录片资源丰富",
        favicon: "N",
        faviconBg: "#e50914",
        tag: "影视",
        tagBg: "rgba(229,9,20,0.12)",
        tagColor: "#e50914",
        accent: "#e50914",
      },
      {
        name: "爱奇艺",
        url: "https://www.iqiyi.com",
        displayUrl: "iqiyi.com",
        desc: "国内领先的视频平台，提供热播剧集、综艺、电影等正版内容",
        favicon: "i",
        faviconBg: "#00a1d6",
        tag: "影视",
        tagBg: "rgba(0,161,214,0.12)",
        tagColor: "#00a1d6",
        accent: "#00a1d6",
      },
      {
        name: "豆瓣",
        url: "https://www.douban.com",
        displayUrl: "douban.com",
        desc: "发现好电影、好书、好音乐的文艺青年聚集地，评分参考首选",
        favicon: "豆",
        faviconBg: "#ff6010",
        tag: "影视评分",
        tagBg: "rgba(255,96,16,0.12)",
        tagColor: "#ff6010",
        accent: "#ff6010",
      },
      {
        name: "Twitch",
        url: "https://www.twitch.tv",
        displayUrl: "twitch.tv",
        desc: "全球最大的游戏直播平台，也涵盖音乐、聊天等多元直播内容",
        favicon: "T",
        faviconBg: "#8b5cf6",
        tag: "直播",
        tagBg: "rgba(139,92,246,0.12)",
        tagColor: "#8b5cf6",
        accent: "#8b5cf6",
      },
    ],
  },
  {
    id: "dev",
    icon: "💻",
    name: "开发工具",
    desc: "程序员的高效工具箱",
    iconBg: "rgba(129,140,248,0.15)",
    sites: [
      {
        name: "GitHub",
        url: "https://github.com",
        displayUrl: "github.com",
        desc: "全球最大的代码托管平台，开源协作和版本控制的首选",
        favicon: "G",
        faviconBg: "#24292e",
        tag: "代码托管",
        tagBg: "rgba(240,246,252,0.1)",
        tagColor: "#c9d1d9",
        accent: "#f0f6fc",
      },
      {
        name: "Stack Overflow",
        url: "https://stackoverflow.com",
        displayUrl: "stackoverflow.com",
        desc: "程序员问答社区，几乎所有技术问题都能找到答案",
        favicon: "S",
        faviconBg: "#f48024",
        tag: "技术问答",
        tagBg: "rgba(244,128,36,0.12)",
        tagColor: "#f48024",
        accent: "#f48024",
      },
      {
        name: "MDN Web Docs",
        url: "https://developer.mozilla.org",
        displayUrl: "developer.mozilla.org",
        desc: "Web 开发权威文档，HTML、CSS、JavaScript 的参考圣经",
        favicon: "MD",
        faviconBg: "#1a1a1a",
        tag: "技术文档",
        tagBg: "rgba(128,128,128,0.15)",
        tagColor: "#8b949e",
        accent: "#000000",
      },
      {
        name: "VS Code",
        url: "https://code.visualstudio.com",
        displayUrl: "code.visualstudio.com",
        desc: "微软出品的免费代码编辑器，插件丰富，开发体验一流",
        favicon: "VS",
        faviconBg: "#007acc",
        tag: "编辑器",
        tagBg: "rgba(0,122,204,0.12)",
        tagColor: "#007acc",
        accent: "#007acc",
      },
      {
        name: "Kubernetes",
        url: "https://kubernetes.io",
        displayUrl: "kubernetes.io",
        desc: "容器编排标准平台，云原生时代的核心基础设施",
        favicon: "K8",
        faviconBg: "#326ce5",
        tag: "DevOps",
        tagBg: "rgba(50,108,229,0.12)",
        tagColor: "#326ce5",
        accent: "#326ce5",
      },
      {
        name: "Docker",
        url: "https://www.docker.com",
        displayUrl: "docker.com",
        desc: "容器化开发部署工具，一次构建到处运行",
        favicon: "D",
        faviconBg: "#2496ed",
        tag: "DevOps",
        tagBg: "rgba(36,150,237,0.12)",
        tagColor: "#2496ed",
        accent: "#2496ed",
      },
      {
        name: "npm",
        url: "https://www.npmjs.com",
        displayUrl: "npmjs.com",
        desc: "Node.js 包管理仓库，前端开发必不可少的依赖管理平台",
        favicon: "np",
        faviconBg: "#cb171e",
        tag: "包管理",
        tagBg: "rgba(203,23,30,0.12)",
        tagColor: "#cb171e",
        accent: "#cb171e",
      },
    ],
  },
  {
    id: "design",
    icon: "🎨",
    name: "设计资源",
    desc: "灵感激发与设计工具集合",
    iconBg: "rgba(236,72,153,0.15)",
    sites: [
      {
        name: "Figma",
        url: "https://www.figma.com",
        displayUrl: "figma.com",
        desc: "协作式界面设计工具，支持实时多人编辑和原型交互",
        favicon: "F",
        faviconBg: "#a259ff",
        tag: "设计工具",
        tagBg: "rgba(162,89,255,0.12)",
        tagColor: "#a259ff",
        accent: "#a259ff",
      },
      {
        name: "Dribbble",
        url: "https://dribbble.com",
        displayUrl: "dribbble.com",
        desc: "设计师作品展示社区，获取 UI/UX 设计灵感的最佳去处",
        favicon: "Dr",
        faviconBg: "#ea4c89",
        tag: "设计灵感",
        tagBg: "rgba(234,76,137,0.12)",
        tagColor: "#ea4c89",
        accent: "#ea4c89",
      },
      {
        name: "Behance",
        url: "https://www.behance.net",
        displayUrl: "behance.net",
        desc: "Adobe 旗下创意作品展示平台，涵盖平面、UI、插画等多领域",
        favicon: "Be",
        faviconBg: "#1769ff",
        tag: "设计灵感",
        tagBg: "rgba(23,105,255,0.12)",
        tagColor: "#1769ff",
        accent: "#1769ff",
      },
      {
        name: "Storyset",
        url: "https://storyset.com",
        displayUrl: "storyset.com",
        desc: "免费可定制插画素材库，支持动画效果和颜色调整",
        favicon: "St",
        faviconBg: "#ff4785",
        tag: "素材资源",
        tagBg: "rgba(255,71,133,0.12)",
        tagColor: "#ff4785",
        accent: "#ff4785",
      },
      {
        name: "unDraw",
        url: "https://undraw.co",
        displayUrl: "undraw.co",
        desc: "开源 MIT 协议的 SVG 插画集合，支持自定义品牌配色",
        favicon: "un",
        faviconBg: "#4daf50",
        tag: "素材资源",
        tagBg: "rgba(77,175,80,0.12)",
        tagColor: "#4daf50",
        accent: "#4daf50",
      },
      {
        name: "Coolors",
        url: "https://coolors.co",
        displayUrl: "coolors.co",
        desc: "快速配色方案生成工具，按空格即可探索新的色彩组合",
        favicon: "Co",
        faviconBg: "#ff7a59",
        tag: "配色工具",
        tagBg: "rgba(255,122,89,0.12)",
        tagColor: "#ff7a59",
        accent: "#ff7a59",
      },
    ],
  },
  {
    id: "social",
    icon: "💬",
    name: "社交媒体",
    desc: "连接世界，分享生活",
    iconBg: "rgba(59,130,246,0.15)",
    sites: [
      {
        name: "X (Twitter)",
        url: "https://twitter.com",
        displayUrl: "twitter.com",
        desc: "全球实时信息分享平台，关注科技、AI 等领域最新动态",
        favicon: "X",
        faviconBg: "#000000",
        tag: "社交",
        tagBg: "rgba(29,155,240,0.12)",
        tagColor: "#1d9bf0",
        accent: "#1d9bf0",
      },
      {
        name: "微博",
        url: "https://weibo.com",
        displayUrl: "weibo.com",
        desc: "中文社交媒体平台，热点话题、明星动态和资讯分享",
        favicon: "微",
        faviconBg: "#e6162d",
        tag: "社交",
        tagBg: "rgba(230,22,45,0.12)",
        tagColor: "#e6162d",
        accent: "#e6162d",
      },
      {
        name: "微信",
        url: "https://weixin.qq.com",
        displayUrl: "weixin.qq.com",
        desc: "国民级社交通信应用，集即时通讯、朋友圈、小程序于一体",
        favicon: "微",
        faviconBg: "#07c160",
        tag: "社交",
        tagBg: "rgba(7,193,96,0.12)",
        tagColor: "#07c160",
        accent: "#07c160",
      },
      {
        name: "Reddit",
        url: "https://www.reddit.com",
        displayUrl: "reddit.com",
        desc: "全球最大的论坛社区，涵盖几乎所有兴趣话题的 Subreddit",
        favicon: "R",
        faviconBg: "#ff4500",
        tag: "社区",
        tagBg: "rgba(255,69,0,0.12)",
        tagColor: "#ff4500",
        accent: "#ff4500",
      },
      {
        name: "Telegram",
        url: "https://t.me",
        displayUrl: "t.me",
        desc: "注重隐私的即时通讯应用，支持大型群组和频道功能",
        favicon: "Tg",
        faviconBg: "#0084ff",
        tag: "社交",
        tagBg: "rgba(0,132,255,0.12)",
        tagColor: "#0084ff",
        accent: "#0084ff",
      },
    ],
  },
  {
    id: "news",
    icon: "📰",
    name: "新闻资讯",
    desc: "保持信息敏锐，洞察行业趋势",
    iconBg: "rgba(255,159,28,0.15)",
    sites: [
      {
        name: "Hacker News",
        url: "https://news.ycombinator.com",
        displayUrl: "news.ycombinator.com",
        desc: "Y Combinator 旗下技术新闻社区，关注创业、编程和科技趋势",
        favicon: "Y",
        faviconBg: "#ff6600",
        tag: "科技",
        tagBg: "rgba(255,102,0,0.12)",
        tagColor: "#ff6600",
        accent: "#ff6600",
      },
      {
        name: "36氪",
        url: "https://www.36kr.com",
        displayUrl: "36kr.com",
        desc: "国内领先的科技商业媒体，聚焦创业、投资和前沿科技",
        favicon: "36",
        faviconBg: "#0a9928",
        tag: "科技",
        tagBg: "rgba(10,153,40,0.12)",
        tagColor: "#0a9928",
        accent: "#0a9928",
      },
      {
        name: "The Verge",
        url: "https://www.theverge.com",
        displayUrl: "theverge.com",
        desc: "科技文化媒体，深度报道科技、科学和未来趋势",
        favicon: "TV",
        faviconBg: "#cb3837",
        tag: "科技",
        tagBg: "rgba(203,56,55,0.12)",
        tagColor: "#cb3837",
        accent: "#cb3837",
      },
      {
        name: "TechCrunch",
        url: "https://www.techcrunch.com",
        displayUrl: "techcrunch.com",
        desc: "专注科技创业和风险投资新闻的权威媒体",
        favicon: "TC",
        faviconBg: "#cf000f",
        tag: "科技",
        tagBg: "rgba(207,0,15,0.12)",
        tagColor: "#cf000f",
        accent: "#cf000f",
      },
      {
        name: "BBC News",
        url: "https://www.bbc.com/news",
        displayUrl: "bbc.com/news",
        desc: "英国广播公司新闻频道，全球视角的权威新闻来源",
        favicon: "B",
        faviconBg: "#bb1919",
        tag: "新闻",
        tagBg: "rgba(187,25,25,0.12)",
        tagColor: "#bb1919",
        accent: "#bb1919",
      },
    ],
  },
  {
    id: "learn",
    icon: "📚",
    name: "学习教育",
    desc: "持续学习，不断成长",
    iconBg: "rgba(16,185,129,0.15)",
    sites: [
      {
        name: "考试酷",
        url: "https://www.examcoo.com/",
        displayUrl: "www.examcoo.com/",
        desc: "免费专为各类学校和培训机构提供考试系统，包括自测练习、组织统一考试、开展知识竞赛、布置课外作业或假期作业、智能组卷、答卷评阅与成绩管理等众多功能；也可用于政府机构、企事业单位内部的入职考试、员工考核、内部培训考试等。",
        favicon: "考",
        faviconBg: "#fe1140",
        tag: "免费考试",
        tagBg: "rgba(254, 17, 64, 0.12)",
        tagColor: "#fe1140",
        accent: "#fe1140c0",
      },
      {
        name: "Coursera",
        url: "https://www.coursera.org",
        displayUrl: "coursera.org",
        desc: "全球顶尖大学和企业的在线课程平台，提供学位证书和专业认证",
        favicon: "C",
        faviconBg: "#0056d3",
        tag: "在线课程",
        tagBg: "rgba(0,86,211,0.12)",
        tagColor: "#0056d3",
        accent: "#0056d3",
      },
      {
        name: "Khan Academy",
        url: "https://www.khanacademy.org",
        displayUrl: "khanacademy.org",
        desc: "非营利教育平台，提供数学、科学等学科的免费优质课程",
        favicon: "K",
        faviconBg: "#14b8a6",
        tag: "免费课程",
        tagBg: "rgba(20,184,166,0.12)",
        tagColor: "#14b8a6",
        accent: "#14b8a6",
      },
      {
        name: "Udemy",
        url: "https://www.udemy.com",
        displayUrl: "udemy.com",
        desc: "全球最大的在线学习市场，涵盖编程、设计、商业等海量课程",
        favicon: "U",
        faviconBg: "#a435f0",
        tag: "在线课程",
        tagBg: "rgba(164,53,240,0.12)",
        tagColor: "#a435f0",
        accent: "#a435f0",
      },
      {
        name: "freeCodeCamp",
        url: "https://www.freecodecamp.org",
        displayUrl: "freecodecamp.org",
        desc: "免费的编程学习平台，通过实战项目学习 Web 开发技能",
        favicon: "f",
        faviconBg: "#f6821f",
        tag: "编程学习",
        tagBg: "rgba(246,130,31,0.12)",
        tagColor: "#f6821f",
        accent: "#f6821f",
      },
      {
        name: "中国大学MOOC",
        url: "https://www.icourse163.org",
        displayUrl: "icourse163.org",
        desc: "汇集国内顶尖高校的公开课平台，免费学习名校优质课程",
        favicon: "Z",
        faviconBg: "#ee3158",
        tag: "公开课",
        tagBg: "rgba(238,49,88,0.12)",
        tagColor: "#ee3158",
        accent: "#ee3158",
      },
    ],
  },
  {
    id: "ai",
    icon: "🤖",
    name: "AI 工具",
    desc: "提升效率的人工智能平台",
    iconBg: "rgba(99,102,241,0.15)",
    sites: [
      {
        name: "ChatGPT",
        url: "https://chat.openai.com",
        displayUrl: "chat.openai.com",
        desc: "OpenAI 推出的智能对话助手，支持文本生成、代码编写、问题解答等多种任务",
        favicon: "C",
        faviconBg: "#10a37f",
        tag: "对话 AI",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "Claude",
        url: "https://claude.ai",
        displayUrl: "claude.ai",
        desc: "Anthropic 开发的 AI 助手，擅长长文本分析、推理和代码生成",
        favicon: "Cl",
        faviconBg: "#a855f7",
        tag: "对话 AI",
        tagBg: "rgba(168,85,247,0.12)",
        tagColor: "#a855f7",
        accent: "#a855f7",
      },
      {
        name: "Midjourney",
        url: "https://www.midjourney.com",
        displayUrl: "midjourney.com",
        desc: "强大的 AI 图像生成工具，输入文字描述即可创作高质量艺术作品",
        favicon: "M",
        faviconBg: "#ec4899",
        tag: "AI 绘画",
        tagBg: "rgba(236,72,153,0.12)",
        tagColor: "#ec4899",
        accent: "#ec4899",
      },
      {
        name: "Stable Diffusion",
        url: "https://stability.ai",
        displayUrl: "stability.ai",
        desc: "开源 AI 图像生成模型，支持本地部署，自由创作无限可能",
        favicon: "S",
        faviconBg: "#f97316",
        tag: "AI 绘画",
        tagBg: "rgba(249,115,22,0.12)",
        tagColor: "#f97316",
        accent: "#f97316",
      },
      {
        name: "Perplexity",
        url: "https://www.perplexity.ai",
        displayUrl: "perplexity.ai",
        desc: "AI 驱动的搜索引擎，结合实时网络信息给出精准答案和引用来源",
        favicon: "P",
        faviconBg: "#06b6d4",
        tag: "AI 搜索",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
      {
        name: "GitHub Copilot",
        url: "https://github.com/features/copilot",
        displayUrl: "github.com/copilot",
        desc: "AI 编程助手，在编辑器中实时提供代码建议和自动补全",
        favicon: "G",
        faviconBg: "#eab308",
        tag: "AI 编程",
        tagBg: "rgba(234,179,8,0.12)",
        tagColor: "#eab308",
        accent: "#eab308",
      },
      {
        name: "Notion AI",
        url: "https://www.notion.so/product/ai",
        displayUrl: "notion.so/product/ai",
        desc: "集成在 Notion 中的 AI 助手，支持写作、总结、翻译等工作流",
        favicon: "N",
        faviconBg: "#3b82f6",
        tag: "AI 写作",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "Runway",
        url: "https://runwayml.com",
        displayUrl: "runwayml.com",
        desc: "AI 视频创作平台，支持文生视频、视频编辑、特效生成等功能",
        favicon: "R",
        faviconBg: "#ef4444",
        tag: "AI 视频",
        tagBg: "rgba(239,68,68,0.12)",
        tagColor: "#ef4444",
        accent: "#ef4444",
      },
      {
        name: "哩布哩布AI",
        url: "https://www.liblib.art/",
        displayUrl: "https://www.liblib.art",
        desc: "AI绘画原创模型分享社区，10万+模型免费下载;原汁原味的webUI、comfyUI，在线AI绘图工具免费使用",
        favicon: "哩",
        faviconBg: "#0867f5",
        tag: "AI 创作",
        tagBg: "rgba(8, 103, 245, 0.12)",
        tagColor: "#0867f5",
        accent: "#0867f53b",
      },
    ],
  },
  {
    id: "wallpaper",
    icon: "🖼️",
    name: "壁纸网站",
    desc: "PC和移动端壁纸网站合计",
    iconBg: "rgba(241, 191, 99, 0.15)",
    sites: [
      {
        name: "故宫壁纸",
        url: "https://www.dpm.org.cn/lights/royal.html",
        displayUrl: "www.dpm.org.cn/lights/royal.html",
        desc: "故宫官网自己出品的壁纸网站",
        favicon: "故",
        faviconBg: "rgb(163, 34, 21)",
        tag: "壁纸",
        tagBg: "rgba(163, 34, 21,.12)",
        tagColor: "rgb(163, 34, 21)",
        accent: "rgb(163, 34, 21)",
      },
      {
        name: "壁纸汇",
        url: "https://www.bizhihui.com/",
        displayUrl: "www.bizhihui.com/",
        desc: "居然有8K壁纸，厉害厉害",
        favicon: "汇",
        faviconBg: "#10a37f",
        tag: "壁纸",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "pexels",
        url: "https://www.pexels.com/zh-cn/",
        displayUrl: "/www.pexels.com/zh-cn/",
        desc: "都是摄影师拍摄的",
        favicon: "P",
        faviconBg: "rgb(57, 57, 57)",
        tag: "壁纸",
        tagBg: "rgba(57, 57, 57,.12)",
        tagColor: "rgb(57, 57, 57)",
        accent: "rgb(57, 57, 57)",
      },
      {
        name: "拾光壁纸",
        url: "https://gallery.timeline.ink/",
        displayUrl: "gallery.timeline.ink/",
        desc: "有网站、小程序和客户端的壁纸网站",
        favicon: "拾",
        faviconBg: "rgb(78, 205, 196)",
        tag: "壁纸",
        tagBg: "rgba(78, 205, 196,.12)",
        tagColor: "rgb(78, 205, 196)",
        accent: "rgb(78, 205, 196)",
      },
      {
        name: "哲风壁纸",
        url: "https://haowallpaper.com/",
        displayUrl: "haowallpaper.com/",
        desc: "有网站和客户端的壁纸网站，免费下载有次数限制，客户端需要付费，一键买断制。",
        favicon: "哲",
       faviconBg: "rgb(57, 57, 57)",
        tag: "壁纸",
        tagBg: "rgba(57, 57, 57,.12)",
        tagColor: "rgb(57, 57, 57)",
        accent: "rgb(57, 57, 57)",
      },
      {
        name: "致美化",
        url: "https://zhutix.com/",
        displayUrl: "zhutix.com/",
        desc: "壁纸只是其中的一部分，他还有电脑主题美化等",
        favicon: "致",
        faviconBg: "#10a37f",
        tag: "壁纸",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "壁纸湖",
        url: "https://bizihu.com/",
        displayUrl: "bizihu.com/",
        desc: "壁纸湖不仅有网站，还有小程序，每月一更，小程序会更新的多",
        favicon: "Cl",
        faviconBg: "#a855f7",
        tag: "壁纸",
        tagBg: "rgba(168,85,247,0.12)",
        tagColor: "#a855f7",
        accent: "#a855f7",
      },
      {
        name: "wallspic",
        url: "https://wallspic.com/",
        displayUrl: "wallspic.com/",
        desc: "免费下载适用于 Windows、Mac、iPhone 和 Android 屏幕的壁纸和桌面背景。",
        favicon: "W",
        faviconBg: "rgb(239, 195, 1)",
        tag: "壁纸",
        tagBg: "rgb(239, 195, 1,.12)",
        tagColor: "rgb(239, 195, 1)",
        accent: "rgb(239, 195, 1)",
      },
      {
        name: "wallsbyjfl",
        url: "https://sites.google.com/view/wallsbyjfl/my-stuff",
        displayUrl: "sites.google.com/view/wallsbyjfl/my-stuff",
        desc: "一个存在google网盘的壁纸网站，所以需要科学上网",
        favicon: "J",
        faviconBg: "#06b6d4",
        tag: "壁纸",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
      {
        name: "gratisography",
        url: "https://gratisography.com/",
        displayUrl: "gratisography.com/",
        desc: "一个UI看起来非常充满活力的壁纸网站",
        favicon: "G",
        faviconBg: "rgb(255, 102, 102)",
        tag: "壁纸",
        tagBg: "rgb(255, 102, 102,.12)",
        tagColor: "rgb(255, 102, 102)",
        accent: "rgb(255, 102, 102)",
      },
      {
        name: "bestwallpapers",
        url: "https://bestwallpapers.net/",
        displayUrl: "bestwallpapers.net/",
        desc: "一个有4K壁纸的网站",
        favicon: "B",
        faviconBg: "#eab308",
        tag: "壁纸",
        tagBg: "rgba(234,179,8,0.12)",
        tagColor: "#eab308",
        accent: "#eab308",
      },
      {
        name: "alphacoders",
        url: "https://wall.alphacoders.com/",
        displayUrl: "wall.alphacoders.com/",
        desc: "一个平平无奇的壁纸网站",
        favicon: "A",
        faviconBg: "#3b82f6",
        tag: "壁纸",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "wallpapershome",
        url: "https://wallpapershome.com/",
        displayUrl: "wallpapershome.com/",
        desc: "一个打开就是4k分类的壁纸网站",
        favicon: "W",
        faviconBg: "#3b82f6",
        tag: "壁纸",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "wallhaven",
        url: "wallhaven.cc/",
        displayUrl: "wallhaven.cc/",
        desc: "一个平平无奇的壁纸网站，国内打不开",
        favicon: "W",
        faviconBg: "#f5089a",
        tag: "壁纸",
        tagBg: "rgba(245, 8, 154,.12)",
        tagColor: "#f5089a",
        accent: "#f5089a",
      },
      {
        name: "wallpaperhub",
        url: "https://www.wallpaperhub.app/",
        displayUrl: "www.wallpaperhub.app/",
        desc: "一个打开就是全屏壁纸的壁纸网站",
        favicon: "W",
        faviconBg: "#06b6d4",
        tag: "壁纸",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
    ],
  },
];
