interface SiteItem {
  name: string;
  url: string;
  displayUrl: string;
  desc: string;
  favicon: string;
  faviconBg: string;
  tag: string;
  tagBg: string;
  tagColor: string;
  accent: string;
}

interface Category {
  id: string;
  icon: string;
  name: string;
  desc: string;
  iconBg: string;
  sites: SiteItem[];
}

export const categories: Category[] = [
  {
    id: "source",
    icon: "🛜",
    name: "资源网站",
    desc: "全网资源网站，涵盖影视、音乐、软件等",
    iconBg: "rgba(241, 132, 99, 0.15)",
    sites: [
      {
        name: "橘子的分享",
        url: "https://orangecj.cn",
        displayUrl: "orangecj.cn",
        desc: "自己看的资源",
        favicon: "橘",
        faviconBg: "#e99527",
        tag: "百度、夸克资源",
        tagBg: "rgba(223, 143, 23, 0.12)",
        tagColor: "#e99527",
        accent: "#e99527",
      },
      {
        name: "3y论坛",
        url: "https://www.3ylt.xyz",
        displayUrl: "www.3ylt.xyz",
        desc: "纯净的网盘资源分享社区",
        favicon: "3y",
        faviconBg: "#c2c2c2",
        tag: "百度、夸克资源",
        tagBg: "rgba(240, 240, 240, 0.12)",
        tagColor: "#c2c2c2",
        accent: "#c2c2c2",
      },
      {
        name: "光鸭资源社",
        url: "https://www.guangya.cc",
        displayUrl: "www.guangya.cc",
        desc: "专注免费分享光鸭云盘资源",
        favicon: "光",
        faviconBg: "#d46b07",
        tag: "光鸭资源",
        tagBg: "rgba(212, 107, 7,.12)",
        tagColor: "#d46b07",
        accent: "#d46b07",
      },
      {
        name: "海盗湾",
        url: "https://thepiratebay.org",
        displayUrl: "thepiratebay.org/",
        desc: "海盗湾磁力网站，需要科学上网",
        favicon: "海",
        faviconBg: "#a3734d",
        tag: "磁力网站",
        tagBg: "rgba(163, 115, 77,.12)",
        tagColor: "#a3734d",
        accent: "#a3734d",
      },
      {
        name: "uindex",
        url: "https://uindex.org",
        displayUrl: "uindex.org",
        desc: "uindex磁力网站，需要科学上网",
        favicon: "U",
        faviconBg: "#5ebb1e",
        tag: "磁力网站",
        tagBg: "rgba(94, 187, 30,.12)",
        tagColor: "#5ebb1e",
        accent: "#5ebb1e",
      },
      {
        name: "纸鸳磁力",
        url: "https://magnet.kiteyuan.info",
        displayUrl: "magnet.kiteyuan.info",
        desc: "纸鸳磁力聚合网站",
        favicon: "鸳",
        faviconBg: "#005bc0",
        tag: "磁力网站",
        tagBg: "rgb(0, 91, 192,.12)",
        tagColor: "#005bc0",
        accent: "#005bc0",
      },
      {
        name: "BT磁力",
        url: "https://www.btbtla.com",
        displayUrl: "www.btbtla.com",
        desc: "BT磁力网站，我用的比较多的磁力网站",
        favicon: "BT",
        faviconBg: "rgb(220, 93, 31)",
        tag: "磁力网站",
        tagBg: "rgb(220, 93, 31,.12)",
        tagColor: "rgb(220, 93, 31)",
        accent: "rgb(220, 93, 31)",
      },
      {
        name: "电影天堂",
        url: "https://www.xl720.com",
        displayUrl: "www.xl720.com",
        desc: "用过的都懂，这个网站版本很多",
        favicon: "影",
        faviconBg: "rgb(31, 138, 204)",
        tag: "磁力网站",
        tagBg: "rgb(31, 138, 204,.12)",
        tagColor: "rgb(31, 138, 204)",
        accent: "rgb(31, 138, 204)",
      },
      {
        name: "6v电影网",
        url: "https://www.6vdy.com",
        displayUrl: "6vdy.com",
        desc: "免费电影电视剧在线站，资源覆盖较广",
        favicon: "6",
        faviconBg: "#34495e",
        tag: "磁力网站",
        tagBg: "rgba(52,73,94,.12)",
        tagColor: "#34495e",
        accent: "#34495e",
      },
      {
        name: "飘花电影网",
        url: "https://www.piaohua.com",
        displayUrl: "piaohua.com",
        desc: "电影在线观看站，华语与欧美片源较多",
        favicon: "飘",
        faviconBg: "#f39c12",
        tag: "磁力网站",
        tagBg: "rgba(243,156,18,.12)",
        tagColor: "#f39c12",
        accent: "#f39c12",
      },
      {
        name: "人人影视",
        url: "https://yyets.com",
        displayUrl: "yyets.com",
        desc: "海外剧集字幕与资源站，美剧英剧口碑好",
        favicon: "人",
        faviconBg: "#2d98da",
        tag: "字幕",
        tagBg: "rgba(45,152,218,.12)",
        tagColor: "#2d98da",
        accent: "#2d98da",
      },
      {
        name: "网盘资源社",
        url: "https://wpzys.org",
        displayUrl: "wpzys.org",
        desc: "免费网盘资源分享社区，可以自己发布资源链接",
        favicon: "网",
        faviconBg: "#f39c12",
        tag: "百度、夸克资源",
        tagBg: "rgba(243,156,18,.12)",
        tagColor: "#f39c12",
        accent: "#f39c12",
      },
      {
        name: "青晨资源站",
        url: "https://www.qingchen86.com",
        displayUrl: "qingchen86.com",
        desc: "全网高清资源分享，可以手动搜索",
        favicon: "青",
        faviconBg: "#f39c12",
        tag: "百度、夸克资源",
        tagBg: "rgba(243,156,18,.12)",
        tagColor: "#f39c12",
        accent: "#f39c12",
      },
      {
        name: "夸克网盘社",
        url: "https://kuakes.com",
        displayUrl: "kuakes.com",
        desc: "夸克网盘资源大全，每日更新电影/电视剧/动漫/短剧合集",
        favicon: "夸",
        faviconBg: "#1458ff",
        tag: "百度、夸克资源",
        tagBg: "rgba(20, 88, 255,.12)",
        tagColor: "#1458ff",
        accent: "#1458ff",
      },
      {
        name: "云盘资源社",
        url: "https://yunpans.com",
        displayUrl: "yunpans.com",
        desc: "专注免费分享网盘资源，优质电影、书籍资料、音乐音频应有尽有",
        favicon: "夸",
        faviconBg: "#066433",
        tag: "百度、夸克资源",
        tagBg: "rgba(6, 100, 51,.12)",
        tagColor: "#066433",
        accent: "#066433",
      },
    ],
  },
  {
    id: "video",
    icon: "🎬",
    name: "影视娱乐",
    desc: "追剧观影一站式直达",
    iconBg: "rgba(239,68,68,0.15)",
    sites: [
      {
        name: "腾讯视频",
        url: "https://v.qq.com",
        displayUrl: "v.qq.com",
        desc: "腾讯旗下视频平台，热播剧集、综艺、体育与自制内容齐全",
        favicon: "腾",
        faviconBg: "#ff9d00",
        tag: "影视",
        tagBg: "rgba(255,157,0,.12)",
        tagColor: "#ff9d00",
        accent: "#ff9d00",
      },
      {
        name: "优酷",
        url: "https://www.youku.com",
        displayUrl: "youku.com",
        desc: "阿里巴巴旗下视频平台，剧集、综艺、动漫与经典内容库丰富",
        favicon: "优",
        faviconBg: "#0c8ed9",
        tag: "影视",
        tagBg: "rgba(12,142,217,.12)",
        tagColor: "#0c8ed9",
        accent: "#0c8ed9",
      },
      {
        name: "芒果TV",
        url: "https://www.mgtv.com",
        displayUrl: "mgtv.com",
        desc: "湖南广电旗下平台，综艺与独播剧集特色鲜明",
        favicon: "芒",
        faviconBg: "#ff8000",
        tag: "影视",
        tagBg: "rgba(255,128,0,.12)",
        tagColor: "#ff8000",
        accent: "#ff8000",
      },
      {
        name: "咪咕视频",
        url: "https://www.miguvideo.com",
        displayUrl: "miguvideo.com",
        desc: "中国移动旗下平台，体育赛事与正版影视资源充足",
        favicon: "咪",
        faviconBg: "#00a0e9",
        tag: "影视",
        tagBg: "rgba(0,160,233,.12)",
        tagColor: "#00a0e9",
        accent: "#00a0e9",
      },
      {
        name: "央视频",
        url: "https://www.yangshipin.cn",
        displayUrl: "yangshipin.cn",
        desc: "中央广播电视总台官方平台，新闻直播与央视内容权威",
        favicon: "央",
        faviconBg: "#e60012",
        tag: "官方影视",
        tagBg: "rgba(230,0,18,.12)",
        tagColor: "#e60012",
        accent: "#e60012",
      },
      {
        name: "西瓜视频",
        url: "https://www.ixigua.com",
        displayUrl: "ixigua.com",
        desc: "字节旗下中视频平台，影视解说与纪录片内容多元",
        favicon: "西",
        faviconBg: "#ff425a",
        tag: "短视频",
        tagBg: "rgba(255,66,90,.12)",
        tagColor: "#ff425a",
        accent: "#ff425a",
      },
      {
        name: "抖音",
        url: "https://www.douyin.com",
        displayUrl: "douyin.com",
        desc: "国民短视频平台，影视剪辑、解说与二创内容活跃",
        favicon: "抖",
        faviconBg: "#fe2c55",
        tag: "短视频",
        tagBg: "rgba(254,44,85,.12)",
        tagColor: "#fe2c55",
        accent: "#fe2c55",
      },
      {
        name: "Disney+",
        url: "https://www.disneyplus.com",
        displayUrl: "disneyplus.com",
        desc: "迪士尼官方流媒体，漫威、星战、皮克斯与动漫全覆盖",
        favicon: "D",
        faviconBg: "#113ccf",
        tag: "影视",
        tagBg: "rgba(17,60,207,.12)",
        tagColor: "#113ccf",
        accent: "#113ccf",
      },
      {
        name: "Prime Video",
        url: "https://www.primevideo.com",
        displayUrl: "primevideo.com",
        desc: "亚马逊流媒体，原创剧集、电影与体育内容丰富",
        favicon: "P",
        faviconBg: "#00a8e1",
        tag: "影视",
        tagBg: "rgba(0,168,225,.12)",
        tagColor: "#00a8e1",
        accent: "#00a8e1",
      },
      {
        name: "Crunchyroll",
        url: "https://www.crunchyroll.com",
        displayUrl: "crunchyroll.com",
        desc: "全球知名动漫流媒体，日番与正版字幕更新及时",
        favicon: "C",
        faviconBg: "#f47521",
        tag: "动漫",
        tagBg: "rgba(244,117,33,.12)",
        tagColor: "#f47521",
        accent: "#f47521",
      },
      {
        name: "IMDb",
        url: "https://www.imdb.com",
        displayUrl: "imdb.com",
        desc: "全球权威影视数据库，评分、资料与榜单参考首选",
        favicon: "I",
        faviconBg: "#f5c518",
        tag: "影视评分",
        tagBg: "rgba(245,197,24,.12)",
        tagColor: "#f5c518",
        accent: "#f5c518",
      },
      {
        name: "猫眼电影",
        url: "https://www.maoyan.com",
        displayUrl: "maoyan.com",
        desc: "国内电影票务与评分平台，院线资讯与购票一体化",
        favicon: "猫",
        faviconBg: "#f6324b",
        tag: "电影票",
        tagBg: "rgba(246,50,75,.12)",
        tagColor: "#f6324b",
        accent: "#f6324b",
      },
      {
        name: "哔哩哔哩",
        url: "https://www.bilibili.com",
        displayUrl: "bilibili.com",
        desc: "年轻人喜爱的弹幕视频网站，涵盖动画、游戏、知识等丰富内容",
        favicon: "B",
        faviconBg: "#fb7299",
        tag: "视频平台",
        tagBg: "rgba(251,114,153,0.12)",
        tagColor: "#fb7299",
        accent: "#fb7299",
      },
      {
        name: "YouTube",
        url: "https://www.youtube.com",
        displayUrl: "youtube.com",
        desc: "全球最大的视频分享平台，海量创作者内容和多元频道",
        favicon: "Y",
        faviconBg: "#ff0000",
        tag: "视频平台",
        tagBg: "rgba(255,0,0,0.12)",
        tagColor: "#ff5252",
        accent: "#ff0000",
      },
      {
        name: "Netflix",
        url: "https://www.netflix.com",
        displayUrl: "netflix.com",
        desc: "全球领先的流媒体平台，原创剧集、电影和纪录片资源丰富",
        favicon: "N",
        faviconBg: "#e50914",
        tag: "影视",
        tagBg: "rgba(229,9,20,0.12)",
        tagColor: "#e50914",
        accent: "#e50914",
      },
      {
        name: "爱奇艺",
        url: "https://www.iqiyi.com",
        displayUrl: "iqiyi.com",
        desc: "国内领先的视频平台，提供热播剧集、综艺、电影等正版内容",
        favicon: "i",
        faviconBg: "#00a1d6",
        tag: "影视",
        tagBg: "rgba(0,161,214,0.12)",
        tagColor: "#00a1d6",
        accent: "#00a1d6",
      },
      {
        name: "豆瓣",
        url: "https://www.douban.com",
        displayUrl: "douban.com",
        desc: "发现好电影、好书、好音乐的文艺青年聚集地，评分参考首选",
        favicon: "豆",
        faviconBg: "#ff6010",
        tag: "影视评分",
        tagBg: "rgba(255,96,16,0.12)",
        tagColor: "#ff6010",
        accent: "#ff6010",
      },
      {
        name: "Twitch",
        url: "https://www.twitch.tv",
        displayUrl: "twitch.tv",
        desc: "全球最大的游戏直播平台，也涵盖音乐、聊天等多元直播内容",
        favicon: "T",
        faviconBg: "#8b5cf6",
        tag: "直播",
        tagBg: "rgba(139,92,246,0.12)",
        tagColor: "#8b5cf6",
        accent: "#8b5cf6",
      },
      {
        name: "爱壹帆",
        url: "https://www.yifan.tv/",
        displayUrl: "www.yifan.tv",
        desc: "海量高清视频免费在线观看",
        favicon: "爱",
        faviconBg: "#6addff",
        tag: "第三方影视",
        tagBg: "rgba(106, 221, 255,.12)",
        tagColor: "#6addff",
        accent: "#6addff",
      },
      {
        name: "泥巴影院",
        url: "https://nbyy.tv",
        displayUrl: "nbyy.tv",
        desc: "海外华人在线影院",
        favicon: "泥",
        faviconBg: "#f3c232",
        tag: "第三方影视",
        tagBg: "rgba(243, 194, 50,.12)",
        tagColor: "#f3c232",
        accent: "#f3c232",
      },
      {
        name: "奈飞工厂",
        url: "https://yanetflix.com",
        displayUrl: "yanetflix.com",
        desc: "一个致力于免费提供Netflix影剧动漫的流媒体播放平台",
        favicon: "奈",
        faviconBg: "#e10916",
        tag: "第三方影视",
        tagBg: "rgba(225, 9, 22,.12)",
        tagColor: "#e10916",
        accent: "#e10916",
      },
      {
        name: "爱迪影视",
        url: "https://aidi.tv",
        displayUrl: "aidi.tv",
        desc: "爱迪影视分享4K资源,1080P高清,Netflix奈菲最新电影,韩剧,日剧,电视剧,欧美剧,动漫等在线观看。",
        favicon: "爱",
        faviconBg: "#3fcf92",
        tag: "第三方影视",
        tagBg: "rgba(63, 207, 146,.12)",
        tagColor: "#3fcf92",
        accent: "#3fcf92",
      },
      {
        name: "低调影视",
        url: "https://ddys.tv",
        displayUrl: "ddys.tv",
        desc: "主打日剧、动漫、韩剧的免费高清影视站，更新快、画质好",
        favicon: "低",
        faviconBg: "#7c5cff",
        tag: "第三方影视",
        tagBg: "rgba(124,92,255,.12)",
        tagColor: "#7c5cff",
        accent: "#7c5cff",
      },
      {
        name: "美剧天堂",
        url: "https://www.mjtt01.com",
        displayUrl: "mjtt01.com",
        desc: "专注美剧在线观看与下载，更新及时",
        favicon: "美",
        faviconBg: "#8e44ad",
        tag: "第三方影视",
        tagBg: "rgba(142,68,173,.12)",
        tagColor: "#8e44ad",
        accent: "#8e44ad",
      },
      {
        name: "星帆影视",
        url: "https://www.xingfan.cc",
        displayUrl: "xingfan.cc",
        desc: "免费在线影视站，电影电视剧分类齐全，每日更新",
        favicon: "星",
        faviconBg: "#16a085",
        tag: "第三方影视",
        tagBg: "rgba(22,160,133,.12)",
        tagColor: "#16a085",
        accent: "#16a085",
      },
      {
        name: "欧乐影院",
        url: "https://www.olevod.com",
        displayUrl: "olevod.com",
        desc: "免费在线影视站，电影电视剧分类齐全，还有电视直播",
        favicon: "欧",
        faviconBg: "#ec673f",
        tag: "第三方影视",
        tagBg: "rgba(236, 103, 63,.12)",
        tagColor: "#ec673f",
        accent: "#ec673f",
      },
      {
        name: "嘀哩哩",
        url: "https://www.dilili.com",
        displayUrl: "dilili.com",
        desc: "专注动漫的免费观看站，番剧更新快",
        favicon: "嘀",
        faviconBg: "#ff6b9d",
        tag: "第三方影视",
        tagBg: "rgba(255,107,157,.12)",
        tagColor: "#ff6b9d",
        accent: "#ff6b9d",
      },
      {
        name: "韩剧TV",
        url: "https://www.9hanju.com",
        displayUrl: "9hanju.com",
        desc: "最新韩剧",
        favicon: "韩",
        faviconBg: "#e21d1d",
        tag: "第三方影视",
        tagBg: "rgba(226, 29, 29,.12)",
        tagColor: "#e21d1d",
        accent: "#e21d1d",
      },
      {
        name: "LIBVIO",
        url: "https://www.libvio.cam",
        displayUrl: "libvio.cam",
        desc: "以海外影视资源为主,自建片源,提供下载",
        favicon: "L",
        faviconBg: "#ffb612",
        tag: "第三方影视",
        tagBg: "rgba(255, 182, 18,.12)",
        tagColor: "#ffb612",
        accent: "#ffb612",
      },
      {
        name: "两个BT",
        url: "https://www.bttwo.life",
        displayUrl: "bttwo.life",
        desc: "秒播，打开的快的很",
        favicon: "两",
        faviconBg: "#0bb2e9",
        tag: "第三方影视",
        tagBg: "rgba(11, 178, 233,.12)",
        tagColor: "#0bb2e9",
        accent: "#0bb2e9",
      },
      {
        name: "番茄动漫",
        url: "https://www.fqdm.cc",
        displayUrl: "fqdm.cc",
        desc: "上万高清动漫",
        favicon: "番",
        faviconBg: "#d62224",
        tag: "第三方动漫",
        tagBg: "rgba(214, 34, 36,.12)",
        tagColor: "#d62224",
        accent: "#d62224",
      },
      {
        name: "komiic漫画",
        url: "https://komiic.cc",
        displayUrl: "komiic.cc",
        desc: "资源丰富、操作便捷为核心优势的漫画阅读平台",
        favicon: "K",
        faviconBg: "#4d58a5",
        tag: "漫画",
        tagBg: "rgba(77, 88, 165,.12)",
        tagColor: "#4d58a5",
        accent: "#4d58a5",
      },
      {
        name: "包子漫画",
        url: "https://www.baozimh.com",
        displayUrl: "baozimh.com",
        desc: "提供优质的漫画阅读体验",
        favicon: "包",
        faviconBg: "#ffb612",
        tag: "漫画",
        tagBg: "rgba(255, 182, 18,.12)",
        tagColor: "#ffb612",
        accent: "#ffb612",
      },
      {
        name: "漫画狗",
        url: "https://manhuagou.net",
        displayUrl: "manhuagou.net",
        desc: "免费漫画在线看，最好看的漫画",
        favicon: "番",
        faviconBg: "#4d58a5",
        tag: "漫画",
        tagBg: "rgba(77, 88, 165,.12)",
        tagColor: "#4d58a5",
        accent: "#4d58a5",
      },
    ],
  },
  {
    id: "dev",
    icon: "💻",
    name: "开发工具",
    desc: "程序员的高效工具箱",
    iconBg: "rgba(129,140,248,0.15)",
    sites: [
      {
        name: "GitHub",
        url: "https://github.com",
        displayUrl: "github.com",
        desc: "全球最大的代码托管平台，开源协作和版本控制的首选",
        favicon: "G",
        faviconBg: "#24292e",
        tag: "代码托管",
        tagBg: "rgba(240,246,252,0.1)",
        tagColor: "#c9d1d9",
        accent: "#f0f6fc",
      },
      {
        name: "Stack Overflow",
        url: "https://stackoverflow.com",
        displayUrl: "stackoverflow.com",
        desc: "程序员问答社区，几乎所有技术问题都能找到答案",
        favicon: "S",
        faviconBg: "#f48024",
        tag: "技术问答",
        tagBg: "rgba(244,128,36,0.12)",
        tagColor: "#f48024",
        accent: "#f48024",
      },
      {
        name: "MDN Web Docs",
        url: "https://developer.mozilla.org",
        displayUrl: "developer.mozilla.org",
        desc: "Web 开发权威文档，HTML、CSS、JavaScript 的参考圣经",
        favicon: "MD",
        faviconBg: "#1a1a1a",
        tag: "技术文档",
        tagBg: "rgba(128,128,128,0.15)",
        tagColor: "#8b949e",
        accent: "#000000",
      },
      {
        name: "VS Code",
        url: "https://code.visualstudio.com",
        displayUrl: "code.visualstudio.com",
        desc: "微软出品的免费代码编辑器，插件丰富，开发体验一流",
        favicon: "VS",
        faviconBg: "#007acc",
        tag: "编辑器",
        tagBg: "rgba(0,122,204,0.12)",
        tagColor: "#007acc",
        accent: "#007acc",
      },
      {
        name: "Kubernetes",
        url: "https://kubernetes.io",
        displayUrl: "kubernetes.io",
        desc: "容器编排标准平台，云原生时代的核心基础设施",
        favicon: "K8",
        faviconBg: "#326ce5",
        tag: "DevOps",
        tagBg: "rgba(50,108,229,0.12)",
        tagColor: "#326ce5",
        accent: "#326ce5",
      },
      {
        name: "Docker",
        url: "https://www.docker.com",
        displayUrl: "docker.com",
        desc: "容器化开发部署工具，一次构建到处运行",
        favicon: "D",
        faviconBg: "#2496ed",
        tag: "DevOps",
        tagBg: "rgba(36,150,237,0.12)",
        tagColor: "#2496ed",
        accent: "#2496ed",
      },
      {
        name: "npm",
        url: "https://www.npmjs.com",
        displayUrl: "npmjs.com",
        desc: "Node.js 包管理仓库，前端开发必不可少的依赖管理平台",
        favicon: "np",
        faviconBg: "#cb171e",
        tag: "包管理",
        tagBg: "rgba(203,23,30,0.12)",
        tagColor: "#cb171e",
        accent: "#cb171e",
      },
    ],
  },
  {
    id: "design",
    icon: "🎨",
    name: "设计资源",
    desc: "灵感激发与设计工具集合",
    iconBg: "rgba(236,72,153,0.15)",
    sites: [
      {
        name: "Figma",
        url: "https://www.figma.com",
        displayUrl: "figma.com",
        desc: "协作式界面设计工具，支持实时多人编辑和原型交互",
        favicon: "F",
        faviconBg: "#a259ff",
        tag: "设计工具",
        tagBg: "rgba(162,89,255,0.12)",
        tagColor: "#a259ff",
        accent: "#a259ff",
      },
      {
        name: "Dribbble",
        url: "https://dribbble.com",
        displayUrl: "dribbble.com",
        desc: "设计师作品展示社区，获取 UI/UX 设计灵感的最佳去处",
        favicon: "Dr",
        faviconBg: "#ea4c89",
        tag: "设计灵感",
        tagBg: "rgba(234,76,137,0.12)",
        tagColor: "#ea4c89",
        accent: "#ea4c89",
      },
      {
        name: "Behance",
        url: "https://www.behance.net",
        displayUrl: "behance.net",
        desc: "Adobe 旗下创意作品展示平台，涵盖平面、UI、插画等多领域",
        favicon: "Be",
        faviconBg: "#1769ff",
        tag: "设计灵感",
        tagBg: "rgba(23,105,255,0.12)",
        tagColor: "#1769ff",
        accent: "#1769ff",
      },
      {
        name: "Storyset",
        url: "https://storyset.com",
        displayUrl: "storyset.com",
        desc: "免费可定制插画素材库，支持动画效果和颜色调整",
        favicon: "St",
        faviconBg: "#ff4785",
        tag: "素材资源",
        tagBg: "rgba(255,71,133,0.12)",
        tagColor: "#ff4785",
        accent: "#ff4785",
      },
      {
        name: "unDraw",
        url: "https://undraw.co",
        displayUrl: "undraw.co",
        desc: "开源 MIT 协议的 SVG 插画集合，支持自定义品牌配色",
        favicon: "un",
        faviconBg: "#4daf50",
        tag: "素材资源",
        tagBg: "rgba(77,175,80,0.12)",
        tagColor: "#4daf50",
        accent: "#4daf50",
      },
      {
        name: "Coolors",
        url: "https://coolors.co",
        displayUrl: "coolors.co",
        desc: "快速配色方案生成工具，按空格即可探索新的色彩组合",
        favicon: "Co",
        faviconBg: "#ff7a59",
        tag: "配色工具",
        tagBg: "rgba(255,122,89,0.12)",
        tagColor: "#ff7a59",
        accent: "#ff7a59",
      },
    ],
  },
  {
    id: "social",
    icon: "💬",
    name: "社交媒体",
    desc: "连接世界，分享生活",
    iconBg: "rgba(59,130,246,0.15)",
    sites: [
      {
        name: "X (Twitter)",
        url: "https://twitter.com",
        displayUrl: "twitter.com",
        desc: "全球实时信息分享平台，关注科技、AI 等领域最新动态",
        favicon: "X",
        faviconBg: "#000000",
        tag: "社交",
        tagBg: "rgba(29,155,240,0.12)",
        tagColor: "#1d9bf0",
        accent: "#1d9bf0",
      },
      {
        name: "微博",
        url: "https://weibo.com",
        displayUrl: "weibo.com",
        desc: "中文社交媒体平台，热点话题、明星动态和资讯分享",
        favicon: "微",
        faviconBg: "#e6162d",
        tag: "社交",
        tagBg: "rgba(230,22,45,0.12)",
        tagColor: "#e6162d",
        accent: "#e6162d",
      },
      {
        name: "微信",
        url: "https://weixin.qq.com",
        displayUrl: "weixin.qq.com",
        desc: "国民级社交通信应用，集即时通讯、朋友圈、小程序于一体",
        favicon: "微",
        faviconBg: "#07c160",
        tag: "社交",
        tagBg: "rgba(7,193,96,0.12)",
        tagColor: "#07c160",
        accent: "#07c160",
      },
      {
        name: "Reddit",
        url: "https://www.reddit.com",
        displayUrl: "reddit.com",
        desc: "全球最大的论坛社区，涵盖几乎所有兴趣话题的 Subreddit",
        favicon: "R",
        faviconBg: "#ff4500",
        tag: "社区",
        tagBg: "rgba(255,69,0,0.12)",
        tagColor: "#ff4500",
        accent: "#ff4500",
      },
      {
        name: "Telegram",
        url: "https://t.me",
        displayUrl: "t.me",
        desc: "注重隐私的即时通讯应用，支持大型群组和频道功能",
        favicon: "Tg",
        faviconBg: "#0084ff",
        tag: "社交",
        tagBg: "rgba(0,132,255,0.12)",
        tagColor: "#0084ff",
        accent: "#0084ff",
      },
    ],
  },
  {
    id: "news",
    icon: "📰",
    name: "新闻资讯",
    desc: "保持信息敏锐，洞察行业趋势",
    iconBg: "rgba(255,159,28,0.15)",
    sites: [
      {
        name: "Hacker News",
        url: "https://news.ycombinator.com",
        displayUrl: "news.ycombinator.com",
        desc: "Y Combinator 旗下技术新闻社区，关注创业、编程和科技趋势",
        favicon: "Y",
        faviconBg: "#ff6600",
        tag: "科技",
        tagBg: "rgba(255,102,0,0.12)",
        tagColor: "#ff6600",
        accent: "#ff6600",
      },
      {
        name: "36氪",
        url: "https://www.36kr.com",
        displayUrl: "36kr.com",
        desc: "国内领先的科技商业媒体，聚焦创业、投资和前沿科技",
        favicon: "36",
        faviconBg: "#0a9928",
        tag: "科技",
        tagBg: "rgba(10,153,40,0.12)",
        tagColor: "#0a9928",
        accent: "#0a9928",
      },
      {
        name: "The Verge",
        url: "https://www.theverge.com",
        displayUrl: "theverge.com",
        desc: "科技文化媒体，深度报道科技、科学和未来趋势",
        favicon: "TV",
        faviconBg: "#cb3837",
        tag: "科技",
        tagBg: "rgba(203,56,55,0.12)",
        tagColor: "#cb3837",
        accent: "#cb3837",
      },
      {
        name: "TechCrunch",
        url: "https://www.techcrunch.com",
        displayUrl: "techcrunch.com",
        desc: "专注科技创业和风险投资新闻的权威媒体",
        favicon: "TC",
        faviconBg: "#cf000f",
        tag: "科技",
        tagBg: "rgba(207,0,15,0.12)",
        tagColor: "#cf000f",
        accent: "#cf000f",
      },
      {
        name: "BBC News",
        url: "https://www.bbc.com/news",
        displayUrl: "bbc.com/news",
        desc: "英国广播公司新闻频道，全球视角的权威新闻来源",
        favicon: "B",
        faviconBg: "#bb1919",
        tag: "新闻",
        tagBg: "rgba(187,25,25,0.12)",
        tagColor: "#bb1919",
        accent: "#bb1919",
      },
    ],
  },
  {
    id: "learn",
    icon: "📚",
    name: "学习教育",
    desc: "持续学习，不断成长",
    iconBg: "rgba(16,185,129,0.15)",
    sites: [
      {
        name: "考试酷",
        url: "https://www.examcoo.com/",
        displayUrl: "www.examcoo.com/",
        desc: "免费专为各类学校和培训机构提供考试系统，包括自测练习、组织统一考试、开展知识竞赛、布置课外作业或假期作业、智能组卷、答卷评阅与成绩管理等众多功能；也可用于政府机构、企事业单位内部的入职考试、员工考核、内部培训考试等。",
        favicon: "考",
        faviconBg: "#fe1140",
        tag: "免费考试",
        tagBg: "rgba(254, 17, 64, 0.12)",
        tagColor: "#fe1140",
        accent: "#fe1140c0",
      },
      {
        name: "Coursera",
        url: "https://www.coursera.org",
        displayUrl: "coursera.org",
        desc: "全球顶尖大学和企业的在线课程平台，提供学位证书和专业认证",
        favicon: "C",
        faviconBg: "#0056d3",
        tag: "在线课程",
        tagBg: "rgba(0,86,211,0.12)",
        tagColor: "#0056d3",
        accent: "#0056d3",
      },
      {
        name: "Khan Academy",
        url: "https://www.khanacademy.org",
        displayUrl: "khanacademy.org",
        desc: "非营利教育平台，提供数学、科学等学科的免费优质课程",
        favicon: "K",
        faviconBg: "#14b8a6",
        tag: "免费课程",
        tagBg: "rgba(20,184,166,0.12)",
        tagColor: "#14b8a6",
        accent: "#14b8a6",
      },
      {
        name: "Udemy",
        url: "https://www.udemy.com",
        displayUrl: "udemy.com",
        desc: "全球最大的在线学习市场，涵盖编程、设计、商业等海量课程",
        favicon: "U",
        faviconBg: "#a435f0",
        tag: "在线课程",
        tagBg: "rgba(164,53,240,0.12)",
        tagColor: "#a435f0",
        accent: "#a435f0",
      },
      {
        name: "freeCodeCamp",
        url: "https://www.freecodecamp.org",
        displayUrl: "freecodecamp.org",
        desc: "免费的编程学习平台，通过实战项目学习 Web 开发技能",
        favicon: "f",
        faviconBg: "#f6821f",
        tag: "编程学习",
        tagBg: "rgba(246,130,31,0.12)",
        tagColor: "#f6821f",
        accent: "#f6821f",
      },
      {
        name: "中国大学MOOC",
        url: "https://www.icourse163.org",
        displayUrl: "icourse163.org",
        desc: "汇集国内顶尖高校的公开课平台，免费学习名校优质课程",
        favicon: "Z",
        faviconBg: "#ee3158",
        tag: "公开课",
        tagBg: "rgba(238,49,88,0.12)",
        tagColor: "#ee3158",
        accent: "#ee3158",
      },
      {
        name: "学堂在线",
        url: "https://www.xuetangx.com",
        displayUrl: "xuetangx.com",
        desc: "清华大学发起的慕课平台，汇聚国内外名校课程，多数可免费旁听",
        favicon: "学",
        faviconBg: "#165DFF",
        tag: "名校慕课",
        tagBg: "rgba(22,93,255,0.12)",
        tagColor: "#165DFF",
        accent: "#165DFF",
      },
      {
        name: "国家智慧教育公共服务平台",
        url: "https://www.smartedu.cn",
        displayUrl: "smartedu.cn",
        desc: "教育部官方平台，覆盖基础教育到高等教育，资源全部免费",
        favicon: "智",
        faviconBg: "#D7000F",
        tag: "官方平台",
        tagBg: "rgba(215,0,15,0.12)",
        tagColor: "#D7000F",
        accent: "#D7000F",
      },
      {
        name: "学银在线",
        url: "https://www.xueyinonline.com",
        displayUrl: "xueyinonline.com",
        desc: "超星与国家开放大学共建，提供高校学分课程与通识课",
        favicon: "银",
        faviconBg: "#0078D4",
        tag: "高校课程",
        tagBg: "rgba(0,120,212,0.12)",
        tagColor: "#0078D4",
        accent: "#0078D4",
      },
      {
        name: "超星尔雅",
        url: "https://erya.mooc.chaoxing.com",
        displayUrl: "erya.mooc.chaoxing.com",
        desc: "超星旗下通识教育平台，海量人文、社科、科学类网络课程",
        favicon: "超",
        faviconBg: "#00A0E9",
        tag: "通识课",
        tagBg: "rgba(0,160,233,0.12)",
        tagColor: "#00A0E9",
        accent: "#00A0E9",
      },
      {
        name: "MOOC中国",
        url: "https://www.cmooc.com",
        displayUrl: "mooc.cn",
        desc: "聚合国内外优质慕课资源的导航站，方便一站式查找课程",
        favicon: "M",
        faviconBg: "#7C3AED",
        tag: "课程导航",
        tagBg: "rgba(124,58,237,0.12)",
        tagColor: "#7C3AED",
        accent: "#7C3AED",
      },
      {
        name: "我要自学网",
        url: "https://www.51zxw.net",
        displayUrl: "51zxw.net",
        desc: "办公软件、设计、编程等实操视频教程，基础内容免费",
        favicon: "自",
        faviconBg: "#22C55E",
        tag: "技能实操",
        tagBg: "rgba(34,197,94,0.12)",
        tagColor: "#22C55E",
        accent: "#22C55E",
      },
      {
        name: "慕课网",
        url: "https://www.imooc.com",
        displayUrl: "imooc.com",
        desc: "聚焦IT与编程的实战课程平台，含大量免费入门课",
        favicon: "慕",
        faviconBg: "#1890FF",
        tag: "IT课程",
        tagBg: "rgba(24,144,255,0.12)",
        tagColor: "#1890FF",
        accent: "#1890FF",
      },
      {
        name: "菜鸟教程",
        url: "https://www.runoob.com",
        displayUrl: "runoob.com",
        desc: "编程语法速查与入门首选，覆盖前端、后端、数据库等",
        favicon: "菜",
        faviconBg: "#F97316",
        tag: "编程入门",
        tagBg: "rgba(249,115,22,0.12)",
        tagColor: "#F97316",
        accent: "#F97316",
      },
      {
        name: "网易云课堂",
        url: "https://study.163.com",
        displayUrl: "study.163.com",
        desc: "职业技能提升平台，微专业与实用课程，部分免费",
        favicon: "易",
        faviconBg: "#D0021B",
        tag: "职业技能",
        tagBg: "rgba(208,2,27,0.12)",
        tagColor: "#D0021B",
        accent: "#D0021B",
      },
      {
        name: "网易公开课",
        url: "https://open.163.com",
        displayUrl: "open.163.com",
        desc: "汇集国内外名校公开课时政与人文课程，免费观看",
        favicon: "网",
        faviconBg: "#FF4D4F",
        tag: "名校公开课",
        tagBg: "rgba(255,77,79,0.12)",
        tagColor: "#FF4D4F",
        accent: "#FF4D4F",
      },
      {
        name: "学习强国",
        url: "https://www.xuexi.cn",
        displayUrl: "xuexi.cn",
        desc: "官方学习平台，含时政、人文历史、技能等丰富免费内容",
        favicon: "强",
        faviconBg: "#C7000B",
        tag: "官方学习",
        tagBg: "rgba(199,0,11,0.12)",
        tagColor: "#C7000B",
        accent: "#C7000B",
      },
      {
        name: "国家开放大学",
        url: "https://www.ouchn.edu.cn",
        displayUrl: "ouchn.edu.cn",
        desc: "成人学历继续教育平台，部分开放资源免费学习",
        favicon: "开",
        faviconBg: "#15803D",
        tag: "继续教育",
        tagBg: "rgba(21,128,61,0.12)",
        tagColor: "#15803D",
        accent: "#15803D",
      },
    ],
  },
  {
    id: "ai",
    icon: "🤖",
    name: "AI 工具",
    desc: "提升效率的人工智能平台",
    iconBg: "rgba(99,102,241,0.15)",
    sites: [
      {
        name: "ChatGPT",
        url: "https://chat.openai.com",
        displayUrl: "chat.openai.com",
        desc: "OpenAI 推出的智能对话助手，支持文本生成、代码编写、问题解答等多种任务",
        favicon: "C",
        faviconBg: "#10a37f",
        tag: "对话 AI",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "Claude",
        url: "https://claude.ai",
        displayUrl: "claude.ai",
        desc: "Anthropic 开发的 AI 助手，擅长长文本分析、推理和代码生成",
        favicon: "Cl",
        faviconBg: "#a855f7",
        tag: "对话 AI",
        tagBg: "rgba(168,85,247,0.12)",
        tagColor: "#a855f7",
        accent: "#a855f7",
      },
      {
        name: "Midjourney",
        url: "https://www.midjourney.com",
        displayUrl: "midjourney.com",
        desc: "强大的 AI 图像生成工具，输入文字描述即可创作高质量艺术作品",
        favicon: "M",
        faviconBg: "#ec4899",
        tag: "AI 绘画",
        tagBg: "rgba(236,72,153,0.12)",
        tagColor: "#ec4899",
        accent: "#ec4899",
      },
      {
        name: "Stable Diffusion",
        url: "https://stability.ai",
        displayUrl: "stability.ai",
        desc: "开源 AI 图像生成模型，支持本地部署，自由创作无限可能",
        favicon: "S",
        faviconBg: "#f97316",
        tag: "AI 绘画",
        tagBg: "rgba(249,115,22,0.12)",
        tagColor: "#f97316",
        accent: "#f97316",
      },
      {
        name: "Perplexity",
        url: "https://www.perplexity.ai",
        displayUrl: "perplexity.ai",
        desc: "AI 驱动的搜索引擎，结合实时网络信息给出精准答案和引用来源",
        favicon: "P",
        faviconBg: "#06b6d4",
        tag: "AI 搜索",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
      {
        name: "GitHub Copilot",
        url: "https://github.com/features/copilot",
        displayUrl: "github.com/copilot",
        desc: "AI 编程助手，在编辑器中实时提供代码建议和自动补全",
        favicon: "G",
        faviconBg: "#eab308",
        tag: "AI 编程",
        tagBg: "rgba(234,179,8,0.12)",
        tagColor: "#eab308",
        accent: "#eab308",
      },
      {
        name: "Notion AI",
        url: "https://www.notion.so/product/ai",
        displayUrl: "notion.so/product/ai",
        desc: "集成在 Notion 中的 AI 助手，支持写作、总结、翻译等工作流",
        favicon: "N",
        faviconBg: "#3b82f6",
        tag: "AI 写作",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "Runway",
        url: "https://runwayml.com",
        displayUrl: "runwayml.com",
        desc: "AI 视频创作平台，支持文生视频、视频编辑、特效生成等功能",
        favicon: "R",
        faviconBg: "#ef4444",
        tag: "AI 视频",
        tagBg: "rgba(239,68,68,0.12)",
        tagColor: "#ef4444",
        accent: "#ef4444",
      },
      {
        name: "哩布哩布AI",
        url: "https://www.liblib.art/",
        displayUrl: "https://www.liblib.art",
        desc: "AI绘画原创模型分享社区，10万+模型免费下载;原汁原味的webUI、comfyUI，在线AI绘图工具免费使用",
        favicon: "哩",
        faviconBg: "#0867f5",
        tag: "AI 创作",
        tagBg: "rgba(8, 103, 245, 0.12)",
        tagColor: "#0867f5",
        accent: "#0867f53b",
      },
    ],
  },
  {
    id: "wallpaper",
    icon: "🖼️",
    name: "壁纸网站",
    desc: "PC和移动端壁纸网站合计",
    iconBg: "rgba(241, 191, 99, 0.15)",
    sites: [
      {
        name: "故宫壁纸",
        url: "https://www.dpm.org.cn/lights/royal.html",
        displayUrl: "www.dpm.org.cn/lights/royal.html",
        desc: "故宫官网自己出品的壁纸网站",
        favicon: "故",
        faviconBg: "rgb(163, 34, 21)",
        tag: "壁纸",
        tagBg: "rgba(163, 34, 21,.12)",
        tagColor: "rgb(163, 34, 21)",
        accent: "rgb(163, 34, 21)",
      },
      {
        name: "壁纸汇",
        url: "https://www.bizhihui.com/",
        displayUrl: "www.bizhihui.com/",
        desc: "居然有8K壁纸，厉害厉害",
        favicon: "汇",
        faviconBg: "#10a37f",
        tag: "壁纸",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "pexels",
        url: "https://www.pexels.com/zh-cn/",
        displayUrl: "/www.pexels.com/zh-cn/",
        desc: "都是摄影师拍摄的",
        favicon: "P",
        faviconBg: "rgb(57, 57, 57)",
        tag: "壁纸",
        tagBg: "rgba(57, 57, 57,.12)",
        tagColor: "rgb(57, 57, 57)",
        accent: "rgb(57, 57, 57)",
      },
      {
        name: "拾光壁纸",
        url: "https://gallery.timeline.ink/",
        displayUrl: "gallery.timeline.ink/",
        desc: "有网站、小程序和客户端的壁纸网站",
        favicon: "拾",
        faviconBg: "rgb(78, 205, 196)",
        tag: "壁纸",
        tagBg: "rgba(78, 205, 196,.12)",
        tagColor: "rgb(78, 205, 196)",
        accent: "rgb(78, 205, 196)",
      },
      {
        name: "哲风壁纸",
        url: "https://haowallpaper.com/",
        displayUrl: "haowallpaper.com/",
        desc: "有网站和客户端的壁纸网站，免费下载有次数限制，客户端需要付费，一键买断制。",
        favicon: "哲",
        faviconBg: "rgb(57, 57, 57)",
        tag: "壁纸",
        tagBg: "rgba(57, 57, 57,.12)",
        tagColor: "rgb(57, 57, 57)",
        accent: "rgb(57, 57, 57)",
      },
      {
        name: "致美化",
        url: "https://zhutix.com/",
        displayUrl: "zhutix.com/",
        desc: "壁纸只是其中的一部分，他还有电脑主题美化等",
        favicon: "致",
        faviconBg: "#10a37f",
        tag: "壁纸",
        tagBg: "rgba(16,163,127,0.12)",
        tagColor: "#10a37f",
        accent: "#10a37f",
      },
      {
        name: "壁纸湖",
        url: "https://bizihu.com/",
        displayUrl: "bizihu.com/",
        desc: "壁纸湖不仅有网站，还有小程序，每月一更，小程序会更新的多",
        favicon: "Cl",
        faviconBg: "#a855f7",
        tag: "壁纸",
        tagBg: "rgba(168,85,247,0.12)",
        tagColor: "#a855f7",
        accent: "#a855f7",
      },
      {
        name: "wallspic",
        url: "https://wallspic.com/",
        displayUrl: "wallspic.com/",
        desc: "免费下载适用于 Windows、Mac、iPhone 和 Android 屏幕的壁纸和桌面背景。",
        favicon: "W",
        faviconBg: "rgb(239, 195, 1)",
        tag: "壁纸",
        tagBg: "rgb(239, 195, 1,.12)",
        tagColor: "rgb(239, 195, 1)",
        accent: "rgb(239, 195, 1)",
      },
      {
        name: "wallsbyjfl",
        url: "https://sites.google.com/view/wallsbyjfl/my-stuff",
        displayUrl: "sites.google.com/view/wallsbyjfl/my-stuff",
        desc: "一个存在google网盘的壁纸网站，所以需要科学上网",
        favicon: "J",
        faviconBg: "#06b6d4",
        tag: "壁纸",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
      {
        name: "gratisography",
        url: "https://gratisography.com/",
        displayUrl: "gratisography.com/",
        desc: "一个UI看起来非常充满活力的壁纸网站",
        favicon: "G",
        faviconBg: "rgb(255, 102, 102)",
        tag: "壁纸",
        tagBg: "rgb(255, 102, 102,.12)",
        tagColor: "rgb(255, 102, 102)",
        accent: "rgb(255, 102, 102)",
      },
      {
        name: "bestwallpapers",
        url: "https://bestwallpapers.net/",
        displayUrl: "bestwallpapers.net/",
        desc: "一个有4K壁纸的网站",
        favicon: "B",
        faviconBg: "#eab308",
        tag: "壁纸",
        tagBg: "rgba(234,179,8,0.12)",
        tagColor: "#eab308",
        accent: "#eab308",
      },
      {
        name: "alphacoders",
        url: "https://wall.alphacoders.com/",
        displayUrl: "wall.alphacoders.com/",
        desc: "一个平平无奇的壁纸网站",
        favicon: "A",
        faviconBg: "#3b82f6",
        tag: "壁纸",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "wallpapershome",
        url: "https://wallpapershome.com/",
        displayUrl: "wallpapershome.com/",
        desc: "一个打开就是4k分类的壁纸网站",
        favicon: "W",
        faviconBg: "#3b82f6",
        tag: "壁纸",
        tagBg: "rgba(59,130,246,0.12)",
        tagColor: "#3b82f6",
        accent: "#3b82f6",
      },
      {
        name: "wallhaven",
        url: "wallhaven.cc/",
        displayUrl: "wallhaven.cc/",
        desc: "一个平平无奇的壁纸网站，国内打不开",
        favicon: "W",
        faviconBg: "#f5089a",
        tag: "壁纸",
        tagBg: "rgba(245, 8, 154,.12)",
        tagColor: "#f5089a",
        accent: "#f5089a",
      },
      {
        name: "wallpaperhub",
        url: "https://www.wallpaperhub.app/",
        displayUrl: "www.wallpaperhub.app/",
        desc: "一个打开就是全屏壁纸的壁纸网站",
        favicon: "W",
        faviconBg: "#06b6d4",
        tag: "壁纸",
        tagBg: "rgba(6,182,212,0.12)",
        tagColor: "#06b6d4",
        accent: "#06b6d4",
      },
    ],
  },
];
