import type { Dish } from './types'

export const categories = ['全部', '凉菜', '素菜', '猪肉', '鸡牛鱼', '汤品', '主食']

export const subCategories = [
  '爽口凉菜',
  '清爽素菜',
  '猪肉小炒',
  '鸡牛鱼特色',
  '营养汤品',
  '主食',
  '预制菜',
  '火锅',
]

// 火锅内部二级分类（仅在左侧选中「火锅」时，于顶部以横向 tab 展示）
export const hotpotGroups = ['锅底', '肉类', '丸子', '蔬菜']

// 本地内联 SVG 占位图：按菜名生成带文字的渐变卡片，无需联网即可显示
function img(name: string): string {
  // 由菜名生成稳定色相
  let hash = 0
  for (let i = 0; i < name.length; i++) hash = (hash * 31 + name.charCodeAt(i)) % 360
  const h1 = hash
  const h2 = (hash + 40) % 360
  const c1 = `hsl(${h1}, 70%, 62%)`
  const c2 = `hsl(${h2}, 72%, 48%)`
  const text = name.length > 6 ? name.slice(0, 6) : name
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200">
  <defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
    <stop offset="0" stop-color="${c1}"/><stop offset="1" stop-color="${c2}"/>
  </linearGradient></defs>
  <rect width="200" height="200" rx="16" fill="url(#g)"/>
  <text x="100" y="108" font-family="-apple-system,'PingFang SC','Microsoft YaHei',sans-serif"
    font-size="30" font-weight="700" fill="#ffffff" text-anchor="middle" dominant-baseline="middle">${text}</text>
</svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}

export const dishes: Dish[] = [
  // ===== 01 爽口凉菜（4 道）=====
  {
    id: '1',
    name: '尖椒皮蛋',
    price: 16,
    image: img("尖椒皮蛋"),
    // image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=200&h=200&fit=crop",
    category: '爽口凉菜',
    tags: ['微辣', '下饭'],
    desc: '皮蛋Q弹，尖椒爽脆，蒜汁入味。经典川味凉菜，开胃解腻。',
    ingredients: {
      main: '皮蛋、青尖椒',
      side: '蒜末、香菜',
      seasonings: '生抽、香醋、辣椒油、花椒油、白糖',
    },
  },
  {
    id: '2',
    name: '拍黄瓜',
    price: 12,
    image: img("拍黄瓜"),
    category: '爽口凉菜',
    tags: ['清爽'],
    desc: '新鲜黄瓜拍裂，拌入蒜香酱汁，口感爽脆，解腻首选。',
  },
  {
    id: '3',
    name: '拌凉粉',
    price: 14,
    image: img("拌凉粉"),
    category: '爽口凉菜',
    tags: ['酸辣'],
    desc: '嫩滑凉粉配红油辣椒，酸辣开胃，夏日必备凉菜。',
  },
  {
    id: '4',
    name: '口水鸡',
    price: 28,
    image: img("口水鸡"),
    category: '爽口凉菜',
    tags: ['麻辣', '招牌'],
    desc: '嫩滑鸡肉淋上秘制红油酱汁，麻辣鲜香，回味悠长。',
  },

  // ===== 02 清爽素菜（11 道）=====
  {
    id: '5',
    name: '酸辣土豆丝',
    price: 14,
    image: img("酸辣土豆丝"),
    category: '清爽素菜',
    tags: ['酸辣', '下饭'],
    desc: '土豆切丝清炒，酸辣爽口，开胃下饭。',
  },
  {
    id: '6',
    name: '蒜泥生菜',
    price: 14,
    image: img("蒜泥生菜"),
    category: '清爽素菜',
    tags: ['清爽'],
    desc: '鲜嫩生菜焯水，淋蒜泥蚝油，清淡爽口。',
  },
  {
    id: '7',
    name: '小炒青菜',
    price: 14,
    image: img("小炒青菜"),
    category: '清爽素菜',
    tags: ['清爽'],
    desc: '当季时蔬大火快炒，保持翠绿清甜。',
  },
  {
    id: '8',
    name: '青菜蘑菇',
    price: 16,
    image: img("青菜蘑菇"),
    category: '清爽素菜',
    tags: ['营养'],
    desc: '青菜配鲜蘑菇同炒，鲜味十足。',
  },
  {
    id: '9',
    name: '西红柿鸡蛋',
    price: 16,
    image: img("西红柿鸡蛋"),
    category: '清爽素菜',
    tags: ['家常', '下饭'],
    desc: '酸甜西红柿配滑蛋，汤汁拌饭一绝。',
  },
  {
    id: '10',
    name: '手撕包菜',
    price: 14,
    image: img("手撕包菜"),
    category: '清爽素菜',
    tags: ['微辣'],
    desc: '包菜手撕干煸，焦香微辣，越嚼越香。',
  },
  {
    id: '11',
    name: '苦瓜炒鸡蛋',
    price: 16,
    image: img("苦瓜炒鸡蛋"),
    category: '清爽素菜',
    tags: ['清热'],
    desc: '苦瓜去火配滑蛋，苦中回甘。',
  },
  {
    id: '12',
    name: '辣椒炒蛋',
    price: 16,
    image: img("辣椒炒蛋"),
    category: '清爽素菜',
    tags: ['下饭'],
    desc: '青红椒炒蛋，咸香微辣，简单下饭。',
  },
  {
    id: '13',
    name: '红烧茄子',
    price: 18,
    image: img("红烧茄子"),
    category: '清爽素菜',
    tags: ['下饭'],
    desc: '茄子烧至软糯入味，酱香浓郁。',
  },
  {
    id: '14',
    name: '干锅花菜',
    price: 18,
    image: img("干锅花菜"),
    category: '清爽素菜',
    tags: ['香辣'],
    desc: '花菜干锅煸炒，干香微辣有嚼劲。',
  },
  {
    id: '15',
    name: '干煸四季豆',
    price: 18,
    image: img("干煸四季豆"),
    category: '清爽素菜',
    tags: ['香辣'],
    desc: '四季豆煸至起皱，配碎肉末干香入味。',
  },

  // ===== 03 猪肉小炒（17 道）=====
  {
    id: '16',
    name: '肉末粉条',
    price: 26,
    image: img("肉末粉条"),
    category: '猪肉小炒',
    tags: ['下饭'],
    desc: '劲道粉条吸满肉酱汁，香辣下饭。',
  },
  {
    id: '17',
    name: '辣椒炒肉',
    price: 28,
    image: img("辣椒炒肉"),
    category: '猪肉小炒',
    tags: ['招牌', '下饭'],
    desc: '湘川风味辣椒炒五花肉，香辣过瘾。',
  },
  {
    id: '18',
    name: '青椒肉丝',
    price: 28,
    image: img("青椒肉丝"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '鲜嫩肉丝配脆爽青椒，经典家常味。',
  },
  {
    id: '19',
    name: '红烧肉',
    price: 36,
    image: img("红烧肉"),
    category: '猪肉小炒',
    tags: ['招牌'],
    desc: '五花肉慢炖上色，肥而不腻，入口即化。',
  },
  {
    id: '20',
    name: '蒜苗回锅肉',
    price: 32,
    image: img("蒜苗回锅肉"),
    category: '猪肉小炒',
    tags: ['招牌'],
    desc: '川菜经典，肥瘦相间回锅肉配蒜苗，香气扑鼻。',
  },
  {
    id: '21',
    name: '蒜苗盐煎肉',
    price: 32,
    image: img("蒜苗盐煎肉"),
    category: '猪肉小炒',
    tags: ['香辣'],
    desc: '五花肉煸出油配蒜苗，干香咸鲜。',
  },
  {
    id: '22',
    name: '蒜苗炒腊肉',
    price: 32,
    image: img("蒜苗炒腊肉"),
    category: '猪肉小炒',
    tags: ['腊味'],
    desc: '烟熏腊肉配蒜苗，咸香下饭。',
  },
  {
    id: '23',
    name: '土豆肉丝',
    price: 24,
    image: img("土豆肉丝"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '土豆丝配肉丝，清爽不腻。',
  },
  {
    id: '24',
    name: '土豆肉片',
    price: 24,
    image: img("土豆肉片"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '软糯土豆片配嫩滑肉片，汤汁浓郁。',
  },
  {
    id: '25',
    name: '土豆回锅肉',
    price: 32,
    image: img("土豆回锅肉"),
    category: '猪肉小炒',
    tags: ['下饭'],
    desc: '回锅肉配土豆片，双重碳水快乐。',
  },
  {
    id: '26',
    name: '尖椒回锅肉',
    price: 32,
    image: img("尖椒回锅肉"),
    category: '猪肉小炒',
    tags: ['香辣'],
    desc: '尖椒与回锅肉同炒，辣香十足。',
  },
  {
    id: '27',
    name: '蒜苔肉丝',
    price: 28,
    image: img("蒜苔肉丝"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '脆嫩蒜苔配肉丝，咸鲜爽口。',
  },
  {
    id: '28',
    name: '香干肉丝',
    price: 26,
    image: img("香干肉丝"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '香干Q弹，肉丝嫩滑，咸香适口。',
  },
  {
    id: '29',
    name: '水煮肉片',
    price: 38,
    image: img("水煮肉片"),
    category: '猪肉小炒',
    tags: ['麻辣', '招牌'],
    desc: '嫩肉片铺满红油花椒，麻辣鲜香。',
  },
  {
    id: '30',
    name: '蒜泥白肉',
    price: 32,
    image: img("蒜泥白肉"),
    category: '猪肉小炒',
    tags: ['麻辣'],
    desc: '薄切五花肉裹蒜泥红油，肥而不腻。',
  },
  {
    id: '31',
    name: '辣椒火腿鸡蛋',
    price: 22,
    image: img("辣椒火腿鸡蛋"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '火腿肠配辣椒鸡蛋，快手下饭。',
  },
  {
    id: '32',
    name: '火腿炒蛋',
    price: 20,
    image: img("火腿炒蛋"),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '火腿丁炒蛋，咸香嫩滑。',
  },
  {
    id: '33',
    name: '莴笋肉片',
    price: 26,
    image: img("莴笋肉片"),
    category: '猪肉小炒',
    tags: ['清爽', '家常'],
    desc: '莴笋脆嫩配滑肉片，清淡爽口。',
  },

  // ===== 04 鸡牛鱼 & 特色（13 道）=====
  {
    id: '34',
    name: '番茄牛腩',
    price: 42,
    image: img("番茄牛腩"),
    category: '鸡牛鱼特色',
    tags: ['营养', '招牌'],
    desc: '牛腩炖至软烂，番茄酸甜开胃。',
  },
  {
    id: '35',
    name: '红烧排骨',
    price: 38,
    image: img("红烧排骨"),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '排骨红烧上色，肉质酥烂入味。',
  },
  {
    id: '36',
    name: '干锅排骨',
    price: 42,
    image: img("干锅排骨"),
    category: '鸡牛鱼特色',
    tags: ['香辣'],
    desc: '排骨干锅煸香，配菜焦香微辣。',
  },
  {
    id: '37',
    name: '干锅鸡',
    price: 42,
    image: img("干锅鸡"),
    category: '鸡牛鱼特色',
    tags: ['香辣'],
    desc: '鸡块干锅煸炒，香辣有嚼劲。',
  },
  {
    id: '38',
    name: '宫保鸡丁',
    price: 32,
    image: img("宫保鸡丁"),
    category: '鸡牛鱼特色',
    tags: ['招牌', '微辣'],
    desc: '鸡丁花生干辣椒同炒，糊辣荔枝口。',
  },
  {
    id: '39',
    name: '生炒鸡',
    price: 38,
    image: img("生炒鸡"),
    category: '鸡牛鱼特色',
    tags: ['家常'],
    desc: '鸡块生炒锁汁，鲜嫩多汁。',
  },
  {
    id: '40',
    name: '红烧猪蹄',
    price: 36,
    image: img("红烧猪蹄"),
    category: '鸡牛鱼特色',
    tags: ['胶原蛋白'],
    desc: '猪蹄红烧软糯，满满胶原。',
  },
  {
    id: '41',
    name: '黄焖鸡',
    price: 34,
    image: img("黄焖鸡"),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '鸡块黄焖入味，配香菇土豆。',
  },
  {
    id: '42',
    name: '黄焖排骨',
    price: 38,
    image: img("黄焖排骨"),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '排骨黄焖至骨肉分离，酱香浓郁。',
  },
  {
    id: '43',
    name: '口蘑虾滑',
    price: 36,
    image: img("口蘑虾滑"),
    category: '鸡牛鱼特色',
    tags: ['鲜', '营养'],
    desc: '口蘑酿虾滑，鲜美弹牙。',
  },
  {
    id: '44',
    name: '麻辣香锅',
    price: 45,
    image: img("麻辣香锅"),
    category: '鸡牛鱼特色',
    tags: ['麻辣'],
    desc: '多种食材一锅炒，麻辣鲜香。',
  },
  {
    id: '45',
    name: '酸菜鱼',
    price: 46,
    image: img("酸菜鱼"),
    category: '鸡牛鱼特色',
    tags: ['酸辣', '招牌'],
    desc: '鱼片滑嫩，酸菜汤底开胃。',
  },
  {
    id: '46',
    name: '水煮鱼片',
    price: 48,
    image: img("水煮鱼片"),
    category: '鸡牛鱼特色',
    tags: ['麻辣'],
    desc: '鱼片铺满红油，麻辣嫩滑。',
  },

  // ===== 05 营养汤品（5 道）=====
  {
    id: '47',
    name: '玉米排骨汤',
    price: 28,
    image: img("玉米排骨汤"),
    category: '营养汤品',
    tags: ['营养', '清淡'],
    desc: '玉米胡萝卜配排骨慢炖，清甜滋补。',
  },
  {
    id: '48',
    name: '丝瓜鸡蛋汤',
    price: 18,
    image: img("丝瓜鸡蛋汤"),
    category: '营养汤品',
    tags: ['清淡'],
    desc: '丝瓜清甜配滑蛋，清爽解腻。',
  },
  {
    id: '49',
    name: '紫菜蛋花汤',
    price: 12,
    image: img("紫菜蛋花汤"),
    category: '营养汤品',
    tags: ['清淡'],
    desc: '紫菜蛋花汤，简单鲜美。',
  },
  {
    id: '50',
    name: '白菜豆腐汤',
    price: 14,
    image: img("白菜豆腐汤"),
    category: '营养汤品',
    tags: ['清淡', '营养'],
    desc: '白菜豆腐同煮，暖胃清淡。',
  },
  {
    id: '51',
    name: '鲫鱼豆腐汤',
    price: 26,
    image: img("鲫鱼豆腐汤"),
    category: '营养汤品',
    tags: ['营养', '滋补'],
    desc: '鲫鱼豆腐奶白汤，鲜美滋补。',
  },

  // ===== 06 主食（9 道）=====
  {
    id: '52',
    name: '鲜香白米饭',
    price: 3,
    image: img("鲜香白米饭"),
    category: '主食',
    tags: ['必点'],
    desc: '东北珍珠米现蒸，粒粒分明。',
  },
  {
    id: '53',
    name: '十三香馄饨',
    price: 12,
    image: img("十三香馄饨"),
    category: '主食',
    tags: ['招牌'],
    desc: '薄皮馄饨配十三香汤底，鲜香暖胃。',
  },
  {
    id: '54',
    name: '饺子',
    price: 15,
    image: img("饺子"),
    category: '主食',
    tags: ['手工'],
    desc: '现包饺子，皮薄馅大。',
  },
  {
    id: '55',
    name: '馒头',
    price: 4,
    image: img("馒头"),
    category: '主食',
    tags: ['手工'],
    desc: '老面发酵馒头，松软香甜。',
  },
  {
    id: '56',
    name: '花卷',
    price: 4,
    image: img("花卷"),
    category: '主食',
    tags: ['手工'],
    desc: '葱香花卷，层层分明。',
  },
  {
    id: '57',
    name: '蛋炒饭',
    price: 14,
    image: img("蛋炒饭"),
    category: '主食',
    tags: ['招牌'],
    desc: '粒粒蛋香裹饭，镬气十足。',
  },
  {
    id: '58',
    name: '老干妈炒饭',
    price: 16,
    image: img("老干妈炒饭"),
    category: '主食',
    tags: ['香辣'],
    desc: '老干妈炒饭，香辣下饭。',
  },
  {
    id: '59',
    name: '杂粮饭',
    price: 5,
    image: img("杂粮饭"),
    category: '主食',
    tags: ['健康'],
    desc: '多种杂粮同煮，健康饱腹。',
  },
  {
    id: '60',
    name: '番茄肉酱意面',
    price: 22,
    image: img("番茄肉酱意面"),
    category: '主食',
    tags: ['西式'],
    desc: '意面配番茄肉酱，酸甜浓郁。',
  },

  // ===== 07 预制菜（3 道）=====
  {
    id: '61',
    name: '烤香肠',
    price: 12,
    image: img("烤香肠"),
    category: '预制菜',
    tags: ['即热'],
    desc: '手工烤肠，加热即食。',
  },
  {
    id: '62',
    name: '咸蛋黄鸡翅',
    price: 26,
    image: img("咸蛋黄鸡翅"),
    category: '预制菜',
    tags: ['招牌'],
    desc: '咸蛋黄裹鸡翅，沙糯咸香。',
  },
  {
    id: '63',
    name: '小酥肉',
    price: 28,
    image: img("小酥肉"),
    category: '预制菜',
    tags: ['酥脆'],
    desc: '炸至金黄小酥肉，外酥里嫩。',
  },

  // ===== 08 火锅（按 subGroup 细分）=====
  // ---- 锅底 ----
  {
    id: '64',
    name: '牛油锅底',
    price: 38,
    image: img("牛油锅底"),
    category: '火锅',
    subGroup: '锅底',
    tags: ['麻辣', '招牌'],
    desc: '经典重庆牛油锅底，麻辣鲜香，越煮越浓。',
  },
  {
    id: '65',
    name: '番茄牛油锅底',
    price: 42,
    image: img("番茄牛油锅底"),
    category: '火锅',
    subGroup: '锅底',
    tags: ['番茄', '招牌'],
    desc: '番茄与牛油融合锅底，酸甜微辣，老少皆宜。',
  },

  // ---- 肉类（涮肉片 / 内脏 / 其他）----
  {
    id: '66',
    name: '麻辣肉片',
    price: 32,
    image: img("麻辣肉片"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['麻辣', '招牌'],
    desc: '嫩肉片裹麻辣腌料，涮煮嫩滑入味。',
  },
  {
    id: '67',
    name: '乌鸡卷',
    price: 36,
    image: img("乌鸡卷"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['营养', '滋补'],
    desc: '乌鸡卷肉质细嫩，汤底更鲜美。',
  },
  {
    id: '68',
    name: '肥牛卷',
    price: 32,
    image: img("肥牛卷"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['必点', '招牌'],
    desc: '雪花肥牛卷，涮几秒即食，肥瘦相间。',
  },
  {
    id: '69',
    name: '肥羊卷',
    price: 32,
    image: img("肥羊卷"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['必点'],
    desc: '内蒙古肥羊卷，鲜嫩无膻。',
  },
  {
    id: '70',
    name: '嫩牛肉片',
    price: 36,
    image: img("嫩牛肉片"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['鲜'],
    desc: '现切嫩牛肉，腌渍入味，久煮不老。',
  },
  {
    id: '71',
    name: '牛上脑',
    price: 42,
    image: img("牛上脑"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['鲜', '招牌'],
    desc: '牛上脑雪花纹理，涮煮嫩香。',
  },
  {
    id: '72',
    name: '吊龙',
    price: 42,
    image: img("吊龙"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['鲜', '招牌'],
    desc: '潮汕牛肉火锅经典部位，肥瘦适中。',
  },
  {
    id: '73',
    name: '羊肉片',
    price: 34,
    image: img("羊肉片"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['鲜'],
    desc: '现切羊肉片，薄嫩无膻。',
  },
  {
    id: '74',
    name: '羊蝎子',
    price: 48,
    image: img("羊蝎子"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['滋补', '招牌'],
    desc: '羊脊骨带髓，炖煮入味，啃骨髓一绝。',
  },
  {
    id: '75',
    name: '精品毛肚',
    price: 38,
    image: img("精品毛肚"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['麻辣', '招牌'],
    desc: '七上八下涮毛肚，脆嫩爽口。',
  },
  {
    id: '76',
    name: '千层肚',
    price: 38,
    image: img("千层肚"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['脆爽'],
    desc: '牛百叶千层肚，涮烫脆嫩。',
  },
  {
    id: '77',
    name: '牛黄喉',
    price: 36,
    image: img("牛黄喉"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['脆爽', '招牌'],
    desc: '牛黄喉脆弹，久煮不老。',
  },
  {
    id: '78',
    name: '鸭肠',
    price: 28,
    image: img("鸭肠"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['脆爽'],
    desc: '鲜鸭肠涮烫脆嫩，蘸料一绝。',
  },
  {
    id: '79',
    name: '猪肝',
    price: 18,
    image: img("猪肝"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['嫩', '营养'],
    desc: '薄切猪肝，涮至变色即食，嫩滑补血。',
  },
  {
    id: '80',
    name: '猪脑',
    price: 26,
    image: img("猪脑"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['绵密', '滋补'],
    desc: '猪脑花涮煮绵密如豆腐，麻辣最配。',
  },
  {
    id: '81',
    name: '午餐肉',
    price: 18,
    image: img("午餐肉"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['经典'],
    desc: '梅林午餐肉，咸香软糯。',
  },
  {
    id: '82',
    name: '鸡肉片',
    price: 28,
    image: img("鸡肉片"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['嫩', '清淡'],
    desc: '鸡胸薄切，涮煮嫩白，清淡不腻。',
  },
  {
    id: '83',
    name: '鹌鹑蛋',
    price: 14,
    image: img("鹌鹑蛋"),
    category: '火锅',
    subGroup: '肉类',
    tags: ['营养'],
    desc: '去壳鹌鹑蛋，煮久入味，Q弹营养。',
  },

  // ---- 丸子 ----
  {
    id: '84',
    name: '牛肉丸',
    price: 22,
    image: img("牛肉丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['弹牙', '必点'],
    desc: '手打牛肉丸，Q弹多汁，煮久不散。',
  },
  {
    id: '85',
    name: '鱼丸',
    price: 18,
    image: img("鱼丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['鲜'],
    desc: '鲜嫩鱼丸，口感细腻，汤鲜丸弹。',
  },
  {
    id: '86',
    name: '虾丸',
    price: 24,
    image: img("虾丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['鲜', '弹牙'],
    desc: '鲜虾手打虾丸，鲜甜弹牙。',
  },
  {
    id: '87',
    name: '贡丸',
    price: 16,
    image: img("贡丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['经典'],
    desc: '经典猪肉贡丸，咸香紧实。',
  },
  {
    id: '88',
    name: '虾滑',
    price: 26,
    image: img("虾滑"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['鲜', '招牌'],
    desc: '手打虾滑，下锅浮起即食，弹嫩鲜甜。',
  },
  {
    id: '89',
    name: '蟹柳',
    price: 16,
    image: img("蟹柳"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['经典'],
    desc: '蟹味柳，软嫩鲜香。',
  },
  {
    id: '90',
    name: '撒尿牛丸',
    price: 24,
    image: img("撒尿牛丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['爆汁', '必点'],
    desc: '爆汁撒尿牛丸，一口咬下汤汁四溢。',
  },
  {
    id: '91',
    name: '芝士丸',
    price: 24,
    image: img("芝士丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['拉丝', '招牌'],
    desc: '芝士爆浆丸，拉丝咸香。',
  },
  {
    id: '92',
    name: '鱼籽丸',
    price: 22,
    image: img("鱼籽丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['鲜', '脆'],
    desc: '鱼籽丸咬开爆籽，口感丰富。',
  },
  {
    id: '93',
    name: '包心鱼丸',
    price: 22,
    image: img("包心鱼丸"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['鲜'],
    desc: '包心鱼丸，外弹内鲜。',
  },
  {
    id: '94',
    name: '亲亲肠',
    price: 16,
    image: img("亲亲肠"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['经典'],
    desc: '一口一个亲亲肠，咸香弹嫩。',
  },
  {
    id: '95',
    name: '脆皮肠',
    price: 16,
    image: img("脆皮肠"),
    category: '火锅',
    subGroup: '丸子',
    tags: ['脆', '经典'],
    desc: '脆皮肠涮煮爆汁，外脆里嫩。',
  },

  // ---- 蔬菜（叶菜 / 根茎 / 菌菇 / 豆制品 / 其他）----
  {
    id: '96',
    name: '蔬菜拼盘',
    price: 18,
    image: img("蔬菜拼盘"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽', '健康'],
    desc: '时令蔬菜拼盘，解腻清口。',
  },
  {
    id: '97',
    name: '菌菇拼盘',
    price: 22,
    image: img("菌菇拼盘"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜', '营养'],
    desc: '多种菌菇拼盘，鲜味十足。',
  },
  {
    id: '98',
    name: '大白菜',
    price: 8,
    image: img("大白菜"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽'],
    desc: '大白菜清甜吸汁，火锅必配。',
  },
  {
    id: '99',
    name: '菠菜',
    price: 10,
    image: img("菠菜"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['营养'],
    desc: '鲜嫩菠菜，涮煮即食。',
  },
  {
    id: '100',
    name: '生菜',
    price: 10,
    image: img("生菜"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽'],
    desc: '脆嫩生菜，清口解腻。',
  },
  {
    id: '101',
    name: '油麦菜',
    price: 10,
    image: img("油麦菜"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽'],
    desc: '油麦菜清香，涮烫爽脆。',
  },
  {
    id: '102',
    name: '茼蒿',
    price: 12,
    image: img("茼蒿"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清香'],
    desc: '茼蒿独特清香，涮锅提味。',
  },
  {
    id: '103',
    name: '土豆片',
    price: 8,
    image: img("土豆片"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['必点'],
    desc: '薄切土豆片，涮煮软糯入味。',
  },
  {
    id: '104',
    name: '莲藕片',
    price: 12,
    image: img("莲藕片"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽'],
    desc: '脆嫩藕片，清热解腻。',
  },
  {
    id: '105',
    name: '山药',
    price: 14,
    image: img("山药"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['营养', '滋补'],
    desc: '铁棍山药涮煮粉糯，养胃滋补。',
  },
  {
    id: '106',
    name: '莴笋片',
    price: 10,
    image: img("莴笋片"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽', '脆'],
    desc: '莴笋片脆嫩，清淡解腻。',
  },
  {
    id: '107',
    name: '萝卜',
    price: 8,
    image: img("萝卜"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清爽'],
    desc: '白萝卜片涮煮清甜。',
  },
  {
    id: '108',
    name: '金针菇',
    price: 10,
    image: img("金针菇"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜'],
    desc: '金针菇爽滑，吸饱汤汁。',
  },
  {
    id: '109',
    name: '香菇',
    price: 12,
    image: img("香菇"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜', '营养'],
    desc: '香菇厚实，煮出菌香。',
  },
  {
    id: '110',
    name: '平菇',
    price: 10,
    image: img("平菇"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜'],
    desc: '平菇软嫩，吸味十足。',
  },
  {
    id: '111',
    name: '杏鲍菇',
    price: 12,
    image: img("杏鲍菇"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜', '脆'],
    desc: '杏鲍菇涮煮脆嫩如肉。',
  },
  {
    id: '112',
    name: '竹荪',
    price: 26,
    image: img("竹荪"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['营养', '招牌'],
    desc: '竹荪网状吸汤，鲜美滋补。',
  },
  {
    id: '113',
    name: '冻豆腐',
    price: 10,
    image: img("冻豆腐"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['吸汁'],
    desc: '冻豆腐孔洞吸汁，一口爆汤。',
  },
  {
    id: '114',
    name: '嫩豆腐',
    price: 8,
    image: img("嫩豆腐"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['嫩', '清淡'],
    desc: '嫩豆腐涮煮即食，豆香软滑。',
  },
  {
    id: '115',
    name: '腐竹',
    price: 12,
    image: img("腐竹"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['经典'],
    desc: '干炸腐竹，煮软后豆香浓郁。',
  },
  {
    id: '116',
    name: '豆皮',
    price: 10,
    image: img("豆皮"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['经典'],
    desc: '薄豆皮涮煮柔韧，吸味一流。',
  },
  {
    id: '117',
    name: '千张',
    price: 10,
    image: img("千张"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['经典'],
    desc: '千张（豆腐皮）切丝，久煮入味。',
  },
  {
    id: '118',
    name: '海带',
    price: 10,
    image: img("海带"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['鲜'],
    desc: '海带结涮煮软糯，鲜味十足。',
  },
  {
    id: '119',
    name: '木耳',
    price: 10,
    image: img("木耳"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['脆', '营养'],
    desc: '黑木耳脆爽，富含胶质。',
  },
  {
    id: '120',
    name: '宽粉',
    price: 10,
    image: img("宽粉"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['招牌', '必点'],
    desc: '红薯宽粉，Q弹顺滑。',
  },
  {
    id: '121',
    name: '玉米',
    price: 12,
    image: img("玉米"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['清甜'],
    desc: '甜玉米段涮煮清甜。',
  },
  {
    id: '122',
    name: '鞭炮笋',
    price: 16,
    image: img("鞭炮笋"),
    category: '火锅',
    subGroup: '蔬菜',
    tags: ['脆爽', '招牌'],
    desc: '鞭炮笋脆嫩爽口，涮煮即食，解腻开胃。',
  },
]

// 日期根据当前真实日期动态计算：取下一个周一到周五的 5 个工作日
const WEEK_LABELS = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
function pad(n: number) {
  return n < 10 ? '0' + n : '' + n
}

export function getWeekDays() {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  // 找到下一个周一（含今天若是周一~周五则取本周，否则取下周）
  const day = today.getDay() // 0=周日 ... 6=周六
  let offsetToMonday: number
  if (day >= 1 && day <= 5) {
    // 今天在周一到周五之间，从本周一开始
    offsetToMonday = 1 - day
  } else {
    // 周六或周日，从下周一
    offsetToMonday = day === 0 ? 1 : 8 - day
  }
  const monday = new Date(today)
  monday.setDate(today.getDate() + offsetToMonday)
  const result = []
  for (let i = 0; i < 5; i++) {
    const d = new Date(monday)
    d.setDate(monday.getDate() + i)
    result.push({
      day: WEEK_LABELS[d.getDay()],
      date: `${pad(d.getMonth() + 1)}/${pad(d.getDate())}`,
    })
  }
  return result
}

export const weekDays = getWeekDays()
