import type { Dish } from './types'

export const categories = ['全部', '凉菜', '素菜', '猪肉', '鸡牛鱼', '汤品', '主食']

export const subCategories = [
  '爽口凉菜',
  '清爽素菜',
  '猪肉小炒',
  '鸡牛鱼特色',
  '营养汤品',
  '主食',
  '预制菜',
]

// Unsplash 关键词占位图（保持本地无外部 CSS 依赖，仅用图片 URL）
const img = (kw: string) =>
  `https://images.unsplash.com/300x300/?${encodeURIComponent(kw)}`

export const dishes: Dish[] = [
  // ===== 01 爽口凉菜（4 道）=====
  {
    id: '1',
    name: '尖椒皮蛋',
    price: 16,
    image: img('century-egg'),
    // image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=200&h=200&fit=crop",
    category: '爽口凉菜',
    tags: ['微辣', '下饭'],
    desc: '皮蛋Q弹，尖椒爽脆，蒜汁入味。经典川味凉菜，开胃解腻。',
    ingredients: {
      main: '皮蛋、青尖椒',
      side: '蒜末、香菜',
      seasonings: '生抽、香醋、辣椒油、花椒油、白糖',
    },
  },
  {
    id: '2',
    name: '拍黄瓜',
    price: 12,
    image: img('cucumber-salad'),
    category: '爽口凉菜',
    tags: ['清爽'],
    desc: '新鲜黄瓜拍裂，拌入蒜香酱汁，口感爽脆，解腻首选。',
  },
  {
    id: '3',
    name: '拌凉粉',
    price: 14,
    image: img('cold-noodles'),
    category: '爽口凉菜',
    tags: ['酸辣'],
    desc: '嫩滑凉粉配红油辣椒，酸辣开胃，夏日必备凉菜。',
  },
  {
    id: '4',
    name: '口水鸡',
    price: 28,
    image: img('chicken'),
    category: '爽口凉菜',
    tags: ['麻辣', '招牌'],
    desc: '嫩滑鸡肉淋上秘制红油酱汁，麻辣鲜香，回味悠长。',
  },

  // ===== 02 清爽素菜（11 道）=====
  {
    id: '5',
    name: '酸辣土豆丝',
    price: 14,
    image: img('potato'),
    category: '清爽素菜',
    tags: ['酸辣', '下饭'],
    desc: '土豆切丝清炒，酸辣爽口，开胃下饭。',
  },
  {
    id: '6',
    name: '蒜泥生菜',
    price: 14,
    image: img('lettuce'),
    category: '清爽素菜',
    tags: ['清爽'],
    desc: '鲜嫩生菜焯水，淋蒜泥蚝油，清淡爽口。',
  },
  {
    id: '7',
    name: '小炒青菜',
    price: 14,
    image: img('greens'),
    category: '清爽素菜',
    tags: ['清爽'],
    desc: '当季时蔬大火快炒，保持翠绿清甜。',
  },
  {
    id: '8',
    name: '青菜蘑菇',
    price: 16,
    image: img('mushroom-vegetable'),
    category: '清爽素菜',
    tags: ['营养'],
    desc: '青菜配鲜蘑菇同炒，鲜味十足。',
  },
  {
    id: '9',
    name: '西红柿鸡蛋',
    price: 16,
    image: img('tomato-egg'),
    category: '清爽素菜',
    tags: ['家常', '下饭'],
    desc: '酸甜西红柿配滑蛋，汤汁拌饭一绝。',
  },
  {
    id: '10',
    name: '手撕包菜',
    price: 14,
    image: img('cabbage'),
    category: '清爽素菜',
    tags: ['微辣'],
    desc: '包菜手撕干煸，焦香微辣，越嚼越香。',
  },
  {
    id: '11',
    name: '苦瓜炒鸡蛋',
    price: 16,
    image: img('bitter-melon'),
    category: '清爽素菜',
    tags: ['清热'],
    desc: '苦瓜去火配滑蛋，苦中回甘。',
  },
  {
    id: '12',
    name: '辣椒炒蛋',
    price: 16,
    image: img('pepper-egg'),
    category: '清爽素菜',
    tags: ['下饭'],
    desc: '青红椒炒蛋，咸香微辣，简单下饭。',
  },
  {
    id: '13',
    name: '红烧茄子',
    price: 18,
    image: img('braised-eggplant'),
    category: '清爽素菜',
    tags: ['下饭'],
    desc: '茄子烧至软糯入味，酱香浓郁。',
  },
  {
    id: '14',
    name: '干锅花菜',
    price: 18,
    image: img('cauliflower'),
    category: '清爽素菜',
    tags: ['香辣'],
    desc: '花菜干锅煸炒，干香微辣有嚼劲。',
  },
  {
    id: '15',
    name: '干煸四季豆',
    price: 18,
    image: img('green-beans'),
    category: '清爽素菜',
    tags: ['香辣'],
    desc: '四季豆煸至起皱，配碎肉末干香入味。',
  },

  // ===== 03 猪肉小炒（17 道）=====
  {
    id: '16',
    name: '肉末粉条',
    price: 26,
    image: img('vermicelli'),
    category: '猪肉小炒',
    tags: ['下饭'],
    desc: '劲道粉条吸满肉酱汁，香辣下饭。',
  },
  {
    id: '17',
    name: '辣椒炒肉',
    price: 28,
    image: img('pepper-pork'),
    category: '猪肉小炒',
    tags: ['招牌', '下饭'],
    desc: '湘川风味辣椒炒五花肉，香辣过瘾。',
  },
  {
    id: '18',
    name: '青椒肉丝',
    price: 28,
    image: img('shredded-pork'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '鲜嫩肉丝配脆爽青椒，经典家常味。',
  },
  {
    id: '19',
    name: '红烧肉',
    price: 36,
    image: img('braised-pork'),
    category: '猪肉小炒',
    tags: ['招牌'],
    desc: '五花肉慢炖上色，肥而不腻，入口即化。',
  },
  {
    id: '20',
    name: '蒜苗回锅肉',
    price: 32,
    image: img('twice-cooked-pork'),
    category: '猪肉小炒',
    tags: ['招牌'],
    desc: '川菜经典，肥瘦相间回锅肉配蒜苗，香气扑鼻。',
  },
  {
    id: '21',
    name: '蒜苗盐煎肉',
    price: 32,
    image: img('fried-pork'),
    category: '猪肉小炒',
    tags: ['香辣'],
    desc: '五花肉煸出油配蒜苗，干香咸鲜。',
  },
  {
    id: '22',
    name: '蒜苗炒腊肉',
    price: 32,
    image: img('bacon'),
    category: '猪肉小炒',
    tags: ['腊味'],
    desc: '烟熏腊肉配蒜苗，咸香下饭。',
  },
  {
    id: '23',
    name: '土豆肉丝',
    price: 24,
    image: img('potato-pork'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '土豆丝配肉丝，清爽不腻。',
  },
  {
    id: '24',
    name: '土豆肉片',
    price: 24,
    image: img('potato-pork-slice'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '软糯土豆片配嫩滑肉片，汤汁浓郁。',
  },
  {
    id: '25',
    name: '土豆回锅肉',
    price: 32,
    image: img('potato-pork'),
    category: '猪肉小炒',
    tags: ['下饭'],
    desc: '回锅肉配土豆片，双重碳水快乐。',
  },
  {
    id: '26',
    name: '尖椒回锅肉',
    price: 32,
    image: img('pepper-pork'),
    category: '猪肉小炒',
    tags: ['香辣'],
    desc: '尖椒与回锅肉同炒，辣香十足。',
  },
  {
    id: '27',
    name: '蒜苔肉丝',
    price: 28,
    image: img('garlic-sprout'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '脆嫩蒜苔配肉丝，咸鲜爽口。',
  },
  {
    id: '28',
    name: '香干肉丝',
    price: 26,
    image: img('dried-tofu'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '香干Q弹，肉丝嫩滑，咸香适口。',
  },
  {
    id: '29',
    name: '水煮肉片',
    price: 38,
    image: img('boiled-pork'),
    category: '猪肉小炒',
    tags: ['麻辣', '招牌'],
    desc: '嫩肉片铺满红油花椒，麻辣鲜香。',
  },
  {
    id: '30',
    name: '蒜泥白肉',
    price: 32,
    image: img('pork-slices'),
    category: '猪肉小炒',
    tags: ['麻辣'],
    desc: '薄切五花肉裹蒜泥红油，肥而不腻。',
  },
  {
    id: '31',
    name: '辣椒火腿鸡蛋',
    price: 22,
    image: img('ham-egg'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '火腿肠配辣椒鸡蛋，快手下饭。',
  },
  {
    id: '32',
    name: '火腿炒蛋',
    price: 20,
    image: img('ham-egg'),
    category: '猪肉小炒',
    tags: ['家常'],
    desc: '火腿丁炒蛋，咸香嫩滑。',
  },

  // ===== 04 鸡牛鱼 & 特色（13 道）=====
  {
    id: '33',
    name: '番茄牛腩',
    price: 42,
    image: img('beef-stew'),
    category: '鸡牛鱼特色',
    tags: ['营养', '招牌'],
    desc: '牛腩炖至软烂，番茄酸甜开胃。',
  },
  {
    id: '34',
    name: '红烧排骨',
    price: 38,
    image: img('pork-ribs'),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '排骨红烧上色，肉质酥烂入味。',
  },
  {
    id: '35',
    name: '干锅排骨',
    price: 42,
    image: img('dry-pot-ribs'),
    category: '鸡牛鱼特色',
    tags: ['香辣'],
    desc: '排骨干锅煸香，配菜焦香微辣。',
  },
  {
    id: '36',
    name: '干锅鸡',
    price: 42,
    image: img('dry-pot-chicken'),
    category: '鸡牛鱼特色',
    tags: ['香辣'],
    desc: '鸡块干锅煸炒，香辣有嚼劲。',
  },
  {
    id: '37',
    name: '宫保鸡丁',
    price: 32,
    image: img('kung-pao'),
    category: '鸡牛鱼特色',
    tags: ['招牌', '微辣'],
    desc: '鸡丁花生干辣椒同炒，糊辣荔枝口。',
  },
  {
    id: '38',
    name: '生炒鸡',
    price: 38,
    image: img('stir-fry-chicken'),
    category: '鸡牛鱼特色',
    tags: ['家常'],
    desc: '鸡块生炒锁汁，鲜嫩多汁。',
  },
  {
    id: '39',
    name: '红烧猪蹄',
    price: 36,
    image: img('pork-trotter'),
    category: '鸡牛鱼特色',
    tags: ['胶原蛋白'],
    desc: '猪蹄红烧软糯，满满胶原。',
  },
  {
    id: '40',
    name: '黄焖鸡',
    price: 34,
    image: img('braised-chicken'),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '鸡块黄焖入味，配香菇土豆。',
  },
  {
    id: '41',
    name: '黄焖排骨',
    price: 38,
    image: img('braised-ribs'),
    category: '鸡牛鱼特色',
    tags: ['招牌'],
    desc: '排骨黄焖至骨肉分离，酱香浓郁。',
  },
  {
    id: '42',
    name: '口蘑虾滑',
    price: 36,
    image: img('shrimp-ball'),
    category: '鸡牛鱼特色',
    tags: ['鲜', '营养'],
    desc: '口蘑酿虾滑，鲜美弹牙。',
  },
  {
    id: '43',
    name: '麻辣香锅',
    price: 45,
    image: img('spicy-pot'),
    category: '鸡牛鱼特色',
    tags: ['麻辣'],
    desc: '多种食材一锅炒，麻辣鲜香。',
  },
  {
    id: '44',
    name: '酸菜鱼',
    price: 46,
    image: img('fish-fillet'),
    category: '鸡牛鱼特色',
    tags: ['酸辣', '招牌'],
    desc: '鱼片滑嫩，酸菜汤底开胃。',
  },
  {
    id: '45',
    name: '水煮鱼片',
    price: 48,
    image: img('boiled-fish'),
    category: '鸡牛鱼特色',
    tags: ['麻辣'],
    desc: '鱼片铺满红油，麻辣嫩滑。',
  },

  // ===== 05 营养汤品（5 道）=====
  {
    id: '46',
    name: '玉米排骨汤',
    price: 28,
    image: img('corn-soup'),
    category: '营养汤品',
    tags: ['营养', '清淡'],
    desc: '玉米胡萝卜配排骨慢炖，清甜滋补。',
  },
  {
    id: '47',
    name: '丝瓜鸡蛋汤',
    price: 18,
    image: img('towel-gourd-soup'),
    category: '营养汤品',
    tags: ['清淡'],
    desc: '丝瓜清甜配滑蛋，清爽解腻。',
  },
  {
    id: '48',
    name: '紫菜蛋花汤',
    price: 12,
    image: img('seaweed-soup'),
    category: '营养汤品',
    tags: ['清淡'],
    desc: '紫菜蛋花汤，简单鲜美。',
  },
  {
    id: '49',
    name: '白菜豆腐汤',
    price: 14,
    image: img('tofu-soup'),
    category: '营养汤品',
    tags: ['清淡', '营养'],
    desc: '白菜豆腐同煮，暖胃清淡。',
  },
  {
    id: '50',
    name: '鲫鱼豆腐汤',
    price: 26,
    image: img('fish-soup'),
    category: '营养汤品',
    tags: ['营养', '滋补'],
    desc: '鲫鱼豆腐奶白汤，鲜美滋补。',
  },

  // ===== 06 主食（9 道）=====
  {
    id: '51',
    name: '鲜香白米饭',
    price: 3,
    image: img('rice'),
    category: '主食',
    tags: ['必点'],
    desc: '东北珍珠米现蒸，粒粒分明。',
  },
  {
    id: '52',
    name: '十三香馄饨',
    price: 12,
    image: img('wonton'),
    category: '主食',
    tags: ['招牌'],
    desc: '薄皮馄饨配十三香汤底，鲜香暖胃。',
  },
  {
    id: '53',
    name: '饺子',
    price: 15,
    image: img('dumpling'),
    category: '主食',
    tags: ['手工'],
    desc: '现包饺子，皮薄馅大。',
  },
  {
    id: '54',
    name: '馒头',
    price: 4,
    image: img('steamed-bun'),
    category: '主食',
    tags: ['手工'],
    desc: '老面发酵馒头，松软香甜。',
  },
  {
    id: '55',
    name: '花卷',
    price: 4,
    image: img('hua-juan'),
    category: '主食',
    tags: ['手工'],
    desc: '葱香花卷，层层分明。',
  },
  {
    id: '56',
    name: '蛋炒饭',
    price: 14,
    image: img('fried-rice'),
    category: '主食',
    tags: ['招牌'],
    desc: '粒粒蛋香裹饭，镬气十足。',
  },
  {
    id: '57',
    name: '老干妈炒饭',
    price: 16,
    image: img('fried-rice'),
    category: '主食',
    tags: ['香辣'],
    desc: '老干妈炒饭，香辣下饭。',
  },
  {
    id: '58',
    name: '杂粮饭',
    price: 5,
    image: img('mixed-grain-rice'),
    category: '主食',
    tags: ['健康'],
    desc: '多种杂粮同煮，健康饱腹。',
  },
  {
    id: '59',
    name: '番茄肉酱意面',
    price: 22,
    image: img('pasta'),
    category: '主食',
    tags: ['西式'],
    desc: '意面配番茄肉酱，酸甜浓郁。',
  },

  // ===== 07 预制菜（3 道）=====
  {
    id: '60',
    name: '烤香肠',
    price: 12,
    image: img('sausage'),
    category: '预制菜',
    tags: ['即热'],
    desc: '手工烤肠，加热即食。',
  },
  {
    id: '61',
    name: '咸蛋黄鸡翅',
    price: 26,
    image: img('chicken-wing'),
    category: '预制菜',
    tags: ['招牌'],
    desc: '咸蛋黄裹鸡翅，沙糯咸香。',
  },
  {
    id: '62',
    name: '小酥肉',
    price: 28,
    image: img('crispy-pork'),
    category: '预制菜',
    tags: ['酥脆'],
    desc: '炸至金黄小酥肉，外酥里嫩。',
  },
]

// 日期根据当前真实日期动态计算：取下一个周一到周五的 5 个工作日
const WEEK_LABELS = ['周日', '周一', '周二', '周三', '周四', '周五', '周六']
function pad(n: number) {
  return n < 10 ? '0' + n : '' + n
}

export function getWeekDays() {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  // 找到下一个周一（含今天若是周一~周五则取本周，否则取下周）
  const day = today.getDay() // 0=周日 ... 6=周六
  let offsetToMonday: number
  if (day >= 1 && day <= 5) {
    // 今天在周一到周五之间，从本周一开始
    offsetToMonday = 1 - day
  } else {
    // 周六或周日，从下周一
    offsetToMonday = day === 0 ? 1 : 8 - day
  }
  const monday = new Date(today)
  monday.setDate(today.getDate() + offsetToMonday)
  const result = []
  for (let i = 0; i < 5; i++) {
    const d = new Date(monday)
    d.setDate(monday.getDate() + i)
    result.push({
      day: WEEK_LABELS[d.getDay()],
      date: `${pad(d.getMonth() + 1)}/${pad(d.getDate())}`,
    })
  }
  return result
}

export const weekDays = getWeekDays()
